## Nettoyage - Eurostat premiers permis

Objectif : nettoyer le fichier Eurostat des premiers permis délivrés aux Camerounais en Europe.

Ce fichier est important pour la question Q2, car il permet d'analyser les motifs d'entrée :
- raisons familiales
- raisons ?ducatives
- raisons professionnelles
- autres raisons

Le fichier contient plusieurs feuilles et les données ne commencent pas directement ? la première ligne.  
Nous allons donc :
1. identifier les feuilles utiles,
2. lire chaque feuille correctement,
3. ajouter une variable `reason`,
4. transformer les années en format long,
5. fusionner les feuilles dans une seule table propre.

In [44]:
import pandas as pd
from pathlib import Path

In [45]:
PROJECT_ROOT = Path("..")
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

EUROPE_PATH = DATA_RAW / "europe"
CLEANED_PATH = DATA_PROCESSED / "cleaned"

CLEANED_PATH.mkdir(parents=True, exist_ok=True)

In [46]:
xls = pd.ExcelFile(EUROPE_PATH / "eurostat_first_permits_cameroon.xlsx")
xls.sheet_names

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

['Sommaire', 'Feuille 1', 'Feuille 2', 'Feuille 3', 'Feuille 4']

In [47]:
sheet1_raw = pd.read_excel(
    EUROPE_PATH / "eurostat_first_permits_cameroon.xlsx",
    sheet_name="Feuille 1",
    header=None
)

sheet1_raw

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Données extraites le13/04/2026 13:19:36 depuis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dataset:,Permis délivrés pour la première fois par rais...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dernière mise à jour:,29/03/2026 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fréquence (relative au temps),NaN,Annuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Raison,NaN,Raisons familiales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Pays de nationalité,NaN,Cameroun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Durée,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Unité de mesure,NaN,Personne,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,TIME,2015,NaN,2016,NaN,2017,NaN,2018,NaN,2019,...,2020,NaN,2021,NaN,2022,NaN,2023,NaN,2024,NaN
11,GEO (Libellés),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Union européenne - 27 pays (à partir de 2020),4605,NaN,4444,NaN,4912,NaN,4899,NaN,4873,...,4507,NaN,6025,NaN,6138,NaN,6381,NaN,6229,NaN
13,Union européenne - 28 pays (2013-2020),4826,NaN,4662,NaN,5153,NaN,5180,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
14,Belgique,695,NaN,610,NaN,600,NaN,732,NaN,790,...,765,NaN,1125,NaN,1055,NaN,1039,NaN,1178,NaN
15,Bulgarie,0,NaN,0,NaN,2,NaN,1,NaN,1,...,0,NaN,1,NaN,6,NaN,1,NaN,5,NaN
16,Tchéquie,15,NaN,9,NaN,9,NaN,7,NaN,7,...,7,NaN,3,NaN,7,NaN,11,NaN,13,NaN
17,Danemark,55,NaN,61,NaN,78,NaN,68,NaN,53,...,64,NaN,45,NaN,64,NaN,66,NaN,77,NaN
18,Allemagne,748,NaN,686,NaN,701,NaN,832,NaN,817,...,753,NaN,1065,NaN,1236,NaN,1461,NaN,1151,NaN
19,Estonie,2,NaN,1,NaN,2,NaN,1,NaN,6,...,5,NaN,10,NaN,11,NaN,8,NaN,8,NaN
20,Irlande,8,NaN,11,NaN,8,NaN,6,NaN,6,...,1,NaN,9,u,6,u,3,u,7,u
21,Grèce,4,NaN,3,NaN,4,NaN,2,NaN,2,...,4,NaN,3,NaN,2,NaN,1,NaN,2,NaN
22,Espagne,181,NaN,180,NaN,194,NaN,209,NaN,195,...,143,NaN,264,NaN,239,NaN,321,NaN,329,NaN
23,France,2196,NaN,2088,NaN,2434,NaN,2197,NaN,2324,...,2229,NaN,2639,NaN,2557,NaN,2397,NaN,2394,NaN
24,Croatie,1,NaN,1,NaN,1,NaN,1,NaN,3,...,4,NaN,2,NaN,0,NaN,0,NaN,3,NaN
25,Italie,330,NaN,446,NaN,507,NaN,434,NaN,279,...,175,NaN,455,NaN,513,NaN,521,NaN,505,NaN
26,Chypre,10,NaN,8,NaN,8,NaN,8,NaN,23,...,25,NaN,27,NaN,22,NaN,24,NaN,11,NaN
27,Lettonie,2,NaN,1,NaN,0,NaN,0,NaN,0,...,1,NaN,0,NaN,0,NaN,1,NaN,2,NaN
28,Lituanie,0,NaN,0,NaN,0,NaN,0,NaN,2,...,0,NaN,2,NaN,2,NaN,2,NaN,0,NaN
29,Luxembourg,65,NaN,52,NaN,65,NaN,102,NaN,78,...,66,NaN,80,NaN,88,NaN,136,NaN,154,NaN
30,Hongrie,26,NaN,33,NaN,19,NaN,27,NaN,2,...,3,NaN,8,NaN,5,NaN,2,NaN,14,NaN
31,Malte,1,NaN,1,NaN,2,NaN,1,NaN,0,...,0,NaN,0,NaN,0,NaN,4,NaN,6,NaN
32,Pays-Bas,36,NaN,35,NaN,48,NaN,38,NaN,45,...,45,NaN,46,NaN,61,NaN,57,NaN,38,NaN
33,Autriche,19,NaN,22,NaN,19,NaN,22,NaN,11,...,12,NaN,13,NaN,21,NaN,27,NaN,14,NaN
34,Pologne,2,NaN,2,NaN,14,NaN,12,NaN,10,...,6,NaN,9,NaN,17,NaN,19,NaN,11,NaN
35,Portugal,16,NaN,11,NaN,4,NaN,21,NaN,17,...,13,NaN,9,NaN,23,NaN,12,NaN,7,NaN
36,Roumanie,9,NaN,2,NaN,9,NaN,7,NaN,12,...,9,NaN,12,NaN,10,NaN,14,NaN,10,NaN
37,Slovénie,1,NaN,0,NaN,3,NaN,2,NaN,3,...,2,NaN,0,NaN,2,NaN,2,NaN,0,NaN
38,Slovaquie,1,NaN,0,NaN,0,NaN,0,NaN,1,...,0,NaN,1,NaN,4,NaN,2,NaN,3,NaN
39,Finlande,68,NaN,69,NaN,69,NaN,55,NaN,63,...,80,NaN,115,NaN,89,NaN,154,NaN,177,NaN
40,Suède,114,NaN,112,NaN,112,NaN,114,NaN,123,...,95,NaN,82,NaN,98,NaN,96,NaN,110,NaN
41,Islande,0,NaN,1,NaN,0,NaN,0,NaN,2,...,2,NaN,1,NaN,3,NaN,4,NaN,0,NaN
42,Liechtenstein,0,NaN,0,NaN,0,NaN,0,NaN,0,...,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
43,Norvège,29,NaN,18,NaN,15,NaN,20,NaN,13,...,6,NaN,16,NaN,25,NaN,26,NaN,27,NaN
44,Suisse,144,NaN,127,NaN,115,NaN,122,NaN,113,...,114,NaN,88,NaN,101,NaN,151,NaN,168,NaN
45,United Kingdom,221,d,218,d,241,NaN,281,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
46,Serbie,:,NaN,:,NaN,:,NaN,:,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,0,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Valeur spéciale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,:,Non disponible,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Attributs d'observations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,d,définition différente (voir métadonnées),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,u,peu fiable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
sheet1_raw = sheet1_raw.drop(columns=[4, 6, 8, 10, 12, 14, 16, 18, 20])

In [49]:
sheet1_raw = sheet1_raw.drop(columns=[2])
sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,Données extraites le13/04/2026 13:19:36 depuis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dataset:,Permis délivrés pour la première fois par rais...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dernière mise à jour:,29/03/2026 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fréquence (relative au temps),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Raison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Pays de nationalité,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Durée,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Unité de mesure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
11,GEO (Libellés),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Union européenne - 27 pays (à partir de 2020),4605,4444,4912,4899,4873,4507,6025,6138,6381,6229
13,Union européenne - 28 pays (2013-2020),4826,4662,5153,5180,:,:,:,:,:,:
14,Belgique,695,610,600,732,790,765,1125,1055,1039,1178
15,Bulgarie,0,0,2,1,1,0,1,6,1,5
16,Tchéquie,15,9,9,7,7,7,3,7,11,13
17,Danemark,55,61,78,68,53,64,45,64,66,77
18,Allemagne,748,686,701,832,817,753,1065,1236,1461,1151
19,Estonie,2,1,2,1,6,5,10,11,8,8
20,Irlande,8,11,8,6,6,1,9,6,3,7
21,Grèce,4,3,4,2,2,4,3,2,1,2
22,Espagne,181,180,194,209,195,143,264,239,321,329
23,France,2196,2088,2434,2197,2324,2229,2639,2557,2397,2394
24,Croatie,1,1,1,1,3,4,2,0,0,3
25,Italie,330,446,507,434,279,175,455,513,521,505
26,Chypre,10,8,8,8,23,25,27,22,24,11
27,Lettonie,2,1,0,0,0,1,0,0,1,2
28,Lituanie,0,0,0,0,2,0,2,2,2,0
29,Luxembourg,65,52,65,102,78,66,80,88,136,154
30,Hongrie,26,33,19,27,2,3,8,5,2,14
31,Malte,1,1,2,1,0,0,0,0,4,6
32,Pays-Bas,36,35,48,38,45,45,46,61,57,38
33,Autriche,19,22,19,22,11,12,13,21,27,14
34,Pologne,2,2,14,12,10,6,9,17,19,11
35,Portugal,16,11,4,21,17,13,9,23,12,7
36,Roumanie,9,2,9,7,12,9,12,10,14,10
37,Slovénie,1,0,3,2,3,2,0,2,2,0
38,Slovaquie,1,0,0,0,1,0,1,4,2,3
39,Finlande,68,69,69,55,63,80,115,89,154,177
40,Suède,114,112,112,114,123,95,82,98,96,110
41,Islande,0,1,0,0,2,2,1,3,4,0
42,Liechtenstein,0,0,0,0,0,0,0,0,0,0
43,Norvège,29,18,15,20,13,6,16,25,26,27
44,Suisse,144,127,115,122,113,114,88,101,151,168
45,United Kingdom,221,218,241,281,:,:,:,:,:,:
46,Serbie,:,:,:,:,:,:,:,:,:,0
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Valeur spéciale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,:,Non disponible,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Attributs d'observations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,d,définition différente (voir métadonnées),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,u,peu fiable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
sheet1_raw = sheet1_raw.drop(index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 47, 48, 49, 50, 51, 52])
sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
10,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
11,GEO (Libellés),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Union européenne - 27 pays (à partir de 2020),4605,4444,4912,4899,4873,4507,6025,6138,6381,6229
13,Union européenne - 28 pays (2013-2020),4826,4662,5153,5180,:,:,:,:,:,:
14,Belgique,695,610,600,732,790,765,1125,1055,1039,1178
15,Bulgarie,0,0,2,1,1,0,1,6,1,5
16,Tchéquie,15,9,9,7,7,7,3,7,11,13
17,Danemark,55,61,78,68,53,64,45,64,66,77
18,Allemagne,748,686,701,832,817,753,1065,1236,1461,1151
19,Estonie,2,1,2,1,6,5,10,11,8,8
20,Irlande,8,11,8,6,6,1,9,6,3,7
21,Grèce,4,3,4,2,2,4,3,2,1,2
22,Espagne,181,180,194,209,195,143,264,239,321,329
23,France,2196,2088,2434,2197,2324,2229,2639,2557,2397,2394
24,Croatie,1,1,1,1,3,4,2,0,0,3
25,Italie,330,446,507,434,279,175,455,513,521,505
26,Chypre,10,8,8,8,23,25,27,22,24,11
27,Lettonie,2,1,0,0,0,1,0,0,1,2
28,Lituanie,0,0,0,0,2,0,2,2,2,0
29,Luxembourg,65,52,65,102,78,66,80,88,136,154
30,Hongrie,26,33,19,27,2,3,8,5,2,14
31,Malte,1,1,2,1,0,0,0,0,4,6
32,Pays-Bas,36,35,48,38,45,45,46,61,57,38
33,Autriche,19,22,19,22,11,12,13,21,27,14
34,Pologne,2,2,14,12,10,6,9,17,19,11
35,Portugal,16,11,4,21,17,13,9,23,12,7
36,Roumanie,9,2,9,7,12,9,12,10,14,10
37,Slovénie,1,0,3,2,3,2,0,2,2,0
38,Slovaquie,1,0,0,0,1,0,1,4,2,3
39,Finlande,68,69,69,55,63,80,115,89,154,177
40,Suède,114,112,112,114,123,95,82,98,96,110
41,Islande,0,1,0,0,2,2,1,3,4,0
42,Liechtenstein,0,0,0,0,0,0,0,0,0,0
43,Norvège,29,18,15,20,13,6,16,25,26,27
44,Suisse,144,127,115,122,113,114,88,101,151,168
45,United Kingdom,221,218,241,281,:,:,:,:,:,:
46,Serbie,:,:,:,:,:,:,:,:,:,0

In [51]:
sheet1_raw = sheet1_raw.replace(":", 0)
sheet1_raw = sheet1_raw[sheet1_raw[0] != "GEO (Libellés)"]
sheet1_raw = sheet1_raw.reset_index(drop=True)
sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Union européenne - 27 pays (à partir de 2020),4605,4444,4912,4899,4873,4507,6025,6138,6381,6229
2,Union européenne - 28 pays (2013-2020),4826,4662,5153,5180,0,0,0,0,0,0
3,Belgique,695,610,600,732,790,765,1125,1055,1039,1178
4,Bulgarie,0,0,2,1,1,0,1,6,1,5
5,Tchéquie,15,9,9,7,7,7,3,7,11,13
6,Danemark,55,61,78,68,53,64,45,64,66,77
7,Allemagne,748,686,701,832,817,753,1065,1236,1461,1151
8,Estonie,2,1,2,1,6,5,10,11,8,8
9,Irlande,8,11,8,6,6,1,9,6,3,7
10,Grèce,4,3,4,2,2,4,3,2,1,2
11,Espagne,181,180,194,209,195,143,264,239,321,329
12,France,2196,2088,2434,2197,2324,2229,2639,2557,2397,2394
13,Croatie,1,1,1,1,3,4,2,0,0,3
14,Italie,330,446,507,434,279,175,455,513,521,505
15,Chypre,10,8,8,8,23,25,27,22,24,11
16,Lettonie,2,1,0,0,0,1,0,0,1,2
17,Lituanie,0,0,0,0,2,0,2,2,2,0
18,Luxembourg,65,52,65,102,78,66,80,88,136,154
19,Hongrie,26,33,19,27,2,3,8,5,2,14
20,Malte,1,1,2,1,0,0,0,0,4,6
21,Pays-Bas,36,35,48,38,45,45,46,61,57,38
22,Autriche,19,22,19,22,11,12,13,21,27,14
23,Pologne,2,2,14,12,10,6,9,17,19,11
24,Portugal,16,11,4,21,17,13,9,23,12,7
25,Roumanie,9,2,9,7,12,9,12,10,14,10
26,Slovénie,1,0,3,2,3,2,0,2,2,0
27,Slovaquie,1,0,0,0,1,0,1,4,2,3
28,Finlande,68,69,69,55,63,80,115,89,154,177
29,Suède,114,112,112,114,123,95,82,98,96,110
30,Islande,0,1,0,0,2,2,1,3,4,0
31,Liechtenstein,0,0,0,0,0,0,0,0,0,0
32,Norvège,29,18,15,20,13,6,16,25,26,27
33,Suisse,144,127,115,122,113,114,88,101,151,168
34,United Kingdom,221,218,241,281,0,0,0,0,0,0
35,Serbie,0,0,0,0,0,0,0,0,0,0

In [52]:
sheet1_raw = sheet1_raw.drop(index=[1, 2])
sheet1_raw

                0     1     3     5     7     9     11    13    15    17    19
0             TIME  2015  2016  2017  2018  2019  2020  2021  2022  2023  2024
3         Belgique   695   610   600   732   790   765  1125  1055  1039  1178
4         Bulgarie     0     0     2     1     1     0     1     6     1     5
5         Tchéquie    15     9     9     7     7     7     3     7    11    13
6         Danemark    55    61    78    68    53    64    45    64    66    77
7        Allemagne   748   686   701   832   817   753  1065  1236  1461  1151
8          Estonie     2     1     2     1     6     5    10    11     8     8
9          Irlande     8    11     8     6     6     1     9     6     3     7
10           Grèce     4     3     4     2     2     4     3     2     1     2
11         Espagne   181   180   194   209   195   143   264   239   321   329
12          France  2196  2088  2434  2197  2324  2229  2639  2557  2397  2394
13         Croatie     1     1     1     1     3     4     2     0     0     3
14          Italie   330   446   507   434   279   175   455   513   521   505
15          Chypre    10     8     8     8    23    25    27    22    24    11
16        Lettonie     2     1     0     0     0     1     0     0     1     2
17        Lituanie     0     0     0     0     2     0     2     2     2     0
18      Luxembourg    65    52    65   102    78    66    80    88   136   154
19         Hongrie    26    33    19    27     2     3     8     5     2    14
20           Malte     1     1     2     1     0     0     0     0     4     6
21        Pays-Bas    36    35    48    38    45    45    46    61    57    38
22        Autriche    19    22    19    22    11    12    13    21    27    14
23         Pologne     2     2    14    12    10     6     9    17    19    11
24        Portugal    16    11     4    21    17    13     9    23    12     7
25        Roumanie     9     2     9     7    12     9    12    10    14    10
26        Slovénie     1     0     3     2     3     2     0     2     2     0
27       Slovaquie     1     0     0     0     1     0     1     4     2     3
28        Finlande    68    69    69    55    63    80   115    89   154   177
29           Suède   114   112   112   114   123    95    82    98    96   110
30         Islande     0     1     0     0     2     2     1     3     4     0
31   Liechtenstein     0     0     0     0     0     0     0     0     0     0
32         Norvège    29    18    15    20    13     6    16    25    26    27
33          Suisse   144   127   115   122   113   114    88   101   151   168
34  United Kingdom   221   218   241   281     0     0     0     0     0     0
35          Serbie     0     0     0     0     0     0     0     0     0     0

In [53]:
sheet1_raw = sheet1_raw.rename(columns={0: "Date"})
sheet1_raw

              Date     1     3     5     7     9    11    13    15    17    19
0             TIME  2015  2016  2017  2018  2019  2020  2021  2022  2023  2024
3         Belgique   695   610   600   732   790   765  1125  1055  1039  1178
4         Bulgarie     0     0     2     1     1     0     1     6     1     5
5         Tchéquie    15     9     9     7     7     7     3     7    11    13
6         Danemark    55    61    78    68    53    64    45    64    66    77
7        Allemagne   748   686   701   832   817   753  1065  1236  1461  1151
8          Estonie     2     1     2     1     6     5    10    11     8     8
9          Irlande     8    11     8     6     6     1     9     6     3     7
10           Grèce     4     3     4     2     2     4     3     2     1     2
11         Espagne   181   180   194   209   195   143   264   239   321   329
12          France  2196  2088  2434  2197  2324  2229  2639  2557  2397  2394
13         Croatie     1     1     1     1     3     4     2     0     0     3
14          Italie   330   446   507   434   279   175   455   513   521   505
15          Chypre    10     8     8     8    23    25    27    22    24    11
16        Lettonie     2     1     0     0     0     1     0     0     1     2
17        Lituanie     0     0     0     0     2     0     2     2     2     0
18      Luxembourg    65    52    65   102    78    66    80    88   136   154
19         Hongrie    26    33    19    27     2     3     8     5     2    14
20           Malte     1     1     2     1     0     0     0     0     4     6
21        Pays-Bas    36    35    48    38    45    45    46    61    57    38
22        Autriche    19    22    19    22    11    12    13    21    27    14
23         Pologne     2     2    14    12    10     6     9    17    19    11
24        Portugal    16    11     4    21    17    13     9    23    12     7
25        Roumanie     9     2     9     7    12     9    12    10    14    10
26        Slovénie     1     0     3     2     3     2     0     2     2     0
27       Slovaquie     1     0     0     0     1     0     1     4     2     3
28        Finlande    68    69    69    55    63    80   115    89   154   177
29           Suède   114   112   112   114   123    95    82    98    96   110
30         Islande     0     1     0     0     2     2     1     3     4     0
31   Liechtenstein     0     0     0     0     0     0     0     0     0     0
32         Norvège    29    18    15    20    13     6    16    25    26    27
33          Suisse   144   127   115   122   113   114    88   101   151   168
34  United Kingdom   221   218   241   281     0     0     0     0     0     0
35          Serbie     0     0     0     0     0     0     0     0     0     0

In [54]:
sheet1_raw.columns = sheet1_raw.iloc[0]
sheet1_raw = sheet1_raw.iloc[1:].reset_index(drop=True)

sheet1_raw = sheet1_raw.rename(columns={"TIME": "Date"})
sheet1_raw = sheet1_raw[sheet1_raw["Date"] != "GEO (Libellés)"]

sheet1_raw["motif"] = "famille"

sheet1_raw

,Date,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,motif
0,Belgique,695,610,600,732,790,765,1125,1055,1039,1178,famille
1,Bulgarie,0,0,2,1,1,0,1,6,1,5,famille
2,Tchéquie,15,9,9,7,7,7,3,7,11,13,famille
3,Danemark,55,61,78,68,53,64,45,64,66,77,famille
4,Allemagne,748,686,701,832,817,753,1065,1236,1461,1151,famille
5,Estonie,2,1,2,1,6,5,10,11,8,8,famille
6,Irlande,8,11,8,6,6,1,9,6,3,7,famille
7,Grèce,4,3,4,2,2,4,3,2,1,2,famille
8,Espagne,181,180,194,209,195,143,264,239,321,329,famille
9,France,2196,2088,2434,2197,2324,2229,2639,2557,2397,2394,famille
10,Croatie,1,1,1,1,3,4,2,0,0,3,famille
11,Italie,330,446,507,434,279,175,455,513,521,505,famille
12,Chypre,10,8,8,8,23,25,27,22,24,11,famille
13,Lettonie,2,1,0,0,0,1,0,0,1,2,famille
14,Lituanie,0,0,0,0,2,0,2,2,2,0,famille
15,Luxembourg,65,52,65,102,78,66,80,88,136,154,famille
16,Hongrie,26,33,19,27,2,3,8,5,2,14,famille
17,Malte,1,1,2,1,0,0,0,0,4,6,famille
18,Pays-Bas,36,35,48,38,45,45,46,61,57,38,famille
19,Autriche,19,22,19,22,11,12,13,21,27,14,famille
20,Pologne,2,2,14,12,10,6,9,17,19,11,famille
21,Portugal,16,11,4,21,17,13,9,23,12,7,famille
22,Roumanie,9,2,9,7,12,9,12,10,14,10,famille
23,Slovénie,1,0,3,2,3,2,0,2,2,0,famille
24,Slovaquie,1,0,0,0,1,0,1,4,2,3,famille
25,Finlande,68,69,69,55,63,80,115,89,154,177,famille
26,Suède,114,112,112,114,123,95,82,98,96,110,famille
27,Islande,0,1,0,0,2,2,1,3,4,0,famille
28,Liechtenstein,0,0,0,0,0,0,0,0,0,0,famille
29,Norvège,29,18,15,20,13,6,16,25,26,27,famille
30,Suisse,144,127,115,122,113,114,88,101,151,168,famille
31,United Kingdom,221,218,241,281,0,0,0,0,0,0,famille
32,Serbie,0,0,0,0,0,0,0,0,0,0,famille

In [55]:
sheet1_raw = sheet1_raw.drop(columns=["motif"], errors="ignore")

In [56]:
sheet1_raw

0             Date  2015  2016  2017  2018  2019  2020  2021  2022  2023  2024
0         Belgique   695   610   600   732   790   765  1125  1055  1039  1178
1         Bulgarie     0     0     2     1     1     0     1     6     1     5
2         Tchéquie    15     9     9     7     7     7     3     7    11    13
3         Danemark    55    61    78    68    53    64    45    64    66    77
4        Allemagne   748   686   701   832   817   753  1065  1236  1461  1151
5          Estonie     2     1     2     1     6     5    10    11     8     8
6          Irlande     8    11     8     6     6     1     9     6     3     7
7            Grèce     4     3     4     2     2     4     3     2     1     2
8          Espagne   181   180   194   209   195   143   264   239   321   329
9           France  2196  2088  2434  2197  2324  2229  2639  2557  2397  2394
10         Croatie     1     1     1     1     3     4     2     0     0     3
11          Italie   330   446   507   434   279   175   455   513   521   505
12          Chypre    10     8     8     8    23    25    27    22    24    11
13        Lettonie     2     1     0     0     0     1     0     0     1     2
14        Lituanie     0     0     0     0     2     0     2     2     2     0
15      Luxembourg    65    52    65   102    78    66    80    88   136   154
16         Hongrie    26    33    19    27     2     3     8     5     2    14
17           Malte     1     1     2     1     0     0     0     0     4     6
18        Pays-Bas    36    35    48    38    45    45    46    61    57    38
19        Autriche    19    22    19    22    11    12    13    21    27    14
20         Pologne     2     2    14    12    10     6     9    17    19    11
21        Portugal    16    11     4    21    17    13     9    23    12     7
22        Roumanie     9     2     9     7    12     9    12    10    14    10
23        Slovénie     1     0     3     2     3     2     0     2     2     0
24       Slovaquie     1     0     0     0     1     0     1     4     2     3
25        Finlande    68    69    69    55    63    80   115    89   154   177
26           Suède   114   112   112   114   123    95    82    98    96   110
27         Islande     0     1     0     0     2     2     1     3     4     0
28   Liechtenstein     0     0     0     0     0     0     0     0     0     0
29         Norvège    29    18    15    20    13     6    16    25    26    27
30          Suisse   144   127   115   122   113   114    88   101   151   168
31  United Kingdom   221   218   241   281     0     0     0     0     0     0
32          Serbie     0     0     0     0     0     0     0     0     0     0

In [57]:
def reshape_first_permits_long(df, motif):
    df = df.copy()

    # Ajouter le motif
    df["motif"] = motif

    # Passer du format large au format long
    df_long = df.melt(
        id_vars=["destination_country", "motif"],
        var_name="year",
        value_name="permits"
    )

    # Nettoyer les types
    df_long["year"] = df_long["year"].astype(int)
    df_long["permits"] = pd.to_numeric(df_long["permits"], errors="coerce").fillna(0).astype(int)

    return df_long

In [58]:
sheet1_raw = sheet1_raw.rename(columns={"Date": "destination_country"})
sheet1_raw

,destination_country,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Belgique,695,610,600,732,790,765,1125,1055,1039,1178
1,Bulgarie,0,0,2,1,1,0,1,6,1,5
2,Tchéquie,15,9,9,7,7,7,3,7,11,13
3,Danemark,55,61,78,68,53,64,45,64,66,77
4,Allemagne,748,686,701,832,817,753,1065,1236,1461,1151
5,Estonie,2,1,2,1,6,5,10,11,8,8
6,Irlande,8,11,8,6,6,1,9,6,3,7
7,Grèce,4,3,4,2,2,4,3,2,1,2
8,Espagne,181,180,194,209,195,143,264,239,321,329
9,France,2196,2088,2434,2197,2324,2229,2639,2557,2397,2394
10,Croatie,1,1,1,1,3,4,2,0,0,3
11,Italie,330,446,507,434,279,175,455,513,521,505
12,Chypre,10,8,8,8,23,25,27,22,24,11
13,Lettonie,2,1,0,0,0,1,0,0,1,2
14,Lituanie,0,0,0,0,2,0,2,2,2,0
15,Luxembourg,65,52,65,102,78,66,80,88,136,154
16,Hongrie,26,33,19,27,2,3,8,5,2,14
17,Malte,1,1,2,1,0,0,0,0,4,6
18,Pays-Bas,36,35,48,38,45,45,46,61,57,38
19,Autriche,19,22,19,22,11,12,13,21,27,14
20,Pologne,2,2,14,12,10,6,9,17,19,11
21,Portugal,16,11,4,21,17,13,9,23,12,7
22,Roumanie,9,2,9,7,12,9,12,10,14,10
23,Slovénie,1,0,3,2,3,2,0,2,2,0
24,Slovaquie,1,0,0,0,1,0,1,4,2,3
25,Finlande,68,69,69,55,63,80,115,89,154,177
26,Suède,114,112,112,114,123,95,82,98,96,110
27,Islande,0,1,0,0,2,2,1,3,4,0
28,Liechtenstein,0,0,0,0,0,0,0,0,0,0
29,Norvège,29,18,15,20,13,6,16,25,26,27
30,Suisse,144,127,115,122,113,114,88,101,151,168
31,United Kingdom,221,218,241,281,0,0,0,0,0,0
32,Serbie,0,0,0,0,0,0,0,0,0,0

In [59]:
def reshape_first_permits_long(df, motif):
    df = df.copy()

    # Ajouter le motif
    df["motif"] = motif

    # Passer du format large au format long
    df_long = df.melt(
        id_vars=["destination_country", "motif"],
        var_name="year",
        value_name="permits"
    )

    # Nettoyer les types
    df_long["year"] = df_long["year"].astype(int)
    df_long["permits"] = pd.to_numeric(df_long["permits"], errors="coerce").fillna(0).astype(int)

    return df_long

In [60]:
sheet1_raw = reshape_first_permits_long(sheet1_raw, "famille")
sheet1_raw

    destination_country    motif  year  permits
0              Belgique  famille  2015      695
1              Bulgarie  famille  2015        0
2              Tchéquie  famille  2015       15
3              Danemark  famille  2015       55
4             Allemagne  famille  2015      748
..                  ...      ...   ...      ...
325       Liechtenstein  famille  2024        0
326             Norvège  famille  2024       27
327              Suisse  famille  2024      168
328      United Kingdom  famille  2024        0
329              Serbie  famille  2024        0

[330 rows x 4 columns]

### Lecture de la deuxième feuille

Nous commençons par ouvrir `Feuille 2` pour repérer :
- o? commencent les vraies données,
- ? quoi ressemblent les colonnes,
- si les années sont en colonnes,
- et o? se trouvent les pays.

In [61]:
sheet2_raw = pd.read_excel(
    EUROPE_PATH / "eurostat_first_permits_cameroon.xlsx",
    sheet_name="Feuille 2",
    header=None
)

sheet2_raw

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Données extraites le13/04/2026 13:19:36 depuis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dataset:,Permis délivrés pour la première fois par rais...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dernière mise à jour:,29/03/2026 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fréquence (relative au temps),NaN,Annuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Raison,NaN,Raisons éducationnelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Pays de nationalité,NaN,Cameroun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Durée,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Unité de mesure,NaN,Personne,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,TIME,2015,NaN,2016,NaN,2017,NaN,2018,NaN,2019,...,2020,NaN,2021,NaN,2022,NaN,2023,NaN,2024,NaN
11,GEO (Libellés),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Union européenne - 27 pays (à partir de 2020),3024,NaN,3381,NaN,3439,NaN,4386,NaN,5322,...,4701,NaN,6584,NaN,6906,NaN,8341,NaN,9084,NaN
13,Union européenne - 28 pays (2013-2020),3240,NaN,3552,NaN,3584,NaN,4510,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
14,Belgique,652,NaN,799,NaN,788,NaN,756,NaN,775,...,665,NaN,1441,NaN,921,NaN,883,NaN,914,NaN
15,Bulgarie,4,NaN,8,NaN,3,NaN,0,NaN,0,...,0,NaN,1,NaN,1,NaN,1,NaN,1,NaN
16,Tchéquie,10,NaN,7,NaN,10,NaN,9,NaN,12,...,14,NaN,23,NaN,19,NaN,17,NaN,8,NaN
17,Danemark,40,NaN,28,NaN,24,NaN,22,NaN,15,...,16,NaN,24,NaN,24,NaN,29,NaN,47,NaN
18,Allemagne,526,NaN,835,NaN,614,NaN,1040,NaN,1692,...,1317,NaN,1292,NaN,1348,NaN,1670,NaN,1788,NaN
19,Estonie,13,NaN,19,NaN,31,NaN,23,NaN,43,...,8,NaN,14,NaN,7,NaN,4,NaN,2,NaN
20,Irlande,13,NaN,4,NaN,11,NaN,9,NaN,12,...,6,NaN,11,u,19,u,15,u,10,u
21,Grèce,1,NaN,1,NaN,3,NaN,1,NaN,8,...,3,NaN,1,NaN,0,NaN,1,NaN,0,NaN
22,Espagne,37,NaN,43,NaN,42,NaN,60,NaN,90,...,104,NaN,103,NaN,102,NaN,118,b,103,NaN
23,France,1201,NaN,1131,NaN,1379,NaN,1767,NaN,2048,...,2062,NaN,2978,NaN,3656,NaN,4490,NaN,5190,NaN
24,Croatie,2,NaN,3,NaN,1,NaN,0,NaN,1,...,0,NaN,0,NaN,0,NaN,0,NaN,1,NaN
25,Italie,278,NaN,194,NaN,233,NaN,327,NaN,197,...,58,NaN,134,NaN,220,NaN,420,NaN,402,NaN
26,Chypre,9,NaN,10,NaN,28,NaN,36,NaN,31,...,22,NaN,29,NaN,13,NaN,2,NaN,3,NaN
27,Lettonie,2,NaN,5,NaN,1,NaN,5,NaN,20,...,55,NaN,142,NaN,141,NaN,71,NaN,21,NaN
28,Lituanie,4,NaN,5,NaN,15,NaN,23,NaN,69,...,52,NaN,70,NaN,83,NaN,158,NaN,203,NaN
29,Luxembourg,6,NaN,5,NaN,6,NaN,13,NaN,14,...,7,NaN,35,NaN,60,NaN,62,NaN,83,NaN
30,Hongrie,79,NaN,116,NaN,87,NaN,35,NaN,25,...,9,NaN,15,NaN,21,NaN,25,NaN,46,NaN
31,Malte,13,NaN,22,NaN,8,NaN,27,NaN,5,...,3,NaN,0,NaN,6,NaN,68,NaN,69,NaN
32,Pays-Bas,22,NaN,23,NaN,29,NaN,34,NaN,36,...,41,NaN,41,NaN,39,NaN,40,NaN,35,NaN
33,Autriche,4,NaN,2,NaN,0,NaN,1,NaN,3,...,2,NaN,4,NaN,5,NaN,12,NaN,7,NaN
34,Pologne,20,NaN,26,NaN,28,NaN,37,NaN,34,...,47,NaN,57,NaN,45,NaN,29,NaN,15,NaN
35,Portugal,8,NaN,25,NaN,3,NaN,10,NaN,11,...,10,NaN,15,NaN,5,NaN,13,NaN,12,NaN
36,Roumanie,12,NaN,19,NaN,27,NaN,60,NaN,59,...,49,NaN,44,NaN,44,NaN,24,NaN,19,NaN
37,Slovénie,0,NaN,1,NaN,0,NaN,0,NaN,0,...,0,NaN,0,NaN,1,NaN,1,NaN,4,NaN
38,Slovaquie,0,NaN,1,NaN,1,NaN,2,NaN,1,...,0,NaN,0,NaN,0,NaN,0,NaN,1,NaN
39,Finlande,44,NaN,34,NaN,30,NaN,16,NaN,9,...,41,NaN,49,NaN,95,NaN,166,NaN,70,NaN
40,Suède,24,NaN,15,NaN,37,NaN,73,NaN,112,...,110,NaN,61,NaN,31,NaN,22,NaN,30,NaN
41,Islande,0,NaN,2,NaN,1,NaN,0,NaN,1,...,2,NaN,0,NaN,1,NaN,3,NaN,4,NaN
42,Liechtenstein,0,NaN,1,NaN,1,NaN,1,NaN,0,...,0,NaN,0,NaN,0,NaN,0,NaN,2,NaN
43,Norvège,24,NaN,28,NaN,42,NaN,33,NaN,37,...,16,NaN,15,NaN,10,NaN,8,NaN,4,NaN
44,Suisse,37,NaN,39,NaN,30,NaN,30,NaN,24,...,33,NaN,32,NaN,49,NaN,48,NaN,75,NaN
45,United Kingdom,216,NaN,171,NaN,145,NaN,124,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
46,Serbie,:,NaN,:,NaN,:,NaN,:,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,1,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Valeur spéciale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,:,Non disponible,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Attributs d'observations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,b,rupture de série,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,u,peu fiable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
def clean_sheet2_etude(excel_path):
    sheet2_raw = pd.read_excel(
        excel_path,
        sheet_name="Feuille 2",
        header=None
    )

    # Supprimer les colonnes 2, 4, 6, ..., 20
    sheet2_raw = sheet2_raw.drop(columns=list(range(2, 21, 2)))

    # Supprimer les lignes inutiles, mais garder la ligne 10 comme entête
    rows_to_drop = list(range(0, 10)) + [11, 12, 13] + list(range(47, 53))
    sheet2_raw = sheet2_raw.drop(index=rows_to_drop)

    # Remplacer ":" par 0
    sheet2_raw = sheet2_raw.replace(":", 0)

    # Mettre la ligne 10 comme entête
    sheet2_raw.columns = sheet2_raw.iloc[0]
    sheet2_raw = sheet2_raw.iloc[1:].reset_index(drop=True)

    # Renommer TIME en destination_country
    sheet2_raw = sheet2_raw.rename(columns={"TIME": "destination_country"})

    # Ajouter la colonne motif
    sheet2_raw["motif"] = "etude"

    return sheet2_raw

In [63]:
sheet2_raw = clean_sheet2_etude(
    EUROPE_PATH / "eurostat_first_permits_cameroon.xlsx"
)

sheet2_raw

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

10,destination_country,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,motif
0,Belgique,652,799,788,756,775,665,1441,921,883,914,etude
1,Bulgarie,4,8,3,0,0,0,1,1,1,1,etude
2,Tchéquie,10,7,10,9,12,14,23,19,17,8,etude
3,Danemark,40,28,24,22,15,16,24,24,29,47,etude
4,Allemagne,526,835,614,1040,1692,1317,1292,1348,1670,1788,etude
5,Estonie,13,19,31,23,43,8,14,7,4,2,etude
6,Irlande,13,4,11,9,12,6,11,19,15,10,etude
7,Grèce,1,1,3,1,8,3,1,0,1,0,etude
8,Espagne,37,43,42,60,90,104,103,102,118,103,etude
9,France,1201,1131,1379,1767,2048,2062,2978,3656,4490,5190,etude
10,Croatie,2,3,1,0,1,0,0,0,0,1,etude
11,Italie,278,194,233,327,197,58,134,220,420,402,etude
12,Chypre,9,10,28,36,31,22,29,13,2,3,etude
13,Lettonie,2,5,1,5,20,55,142,141,71,21,etude
14,Lituanie,4,5,15,23,69,52,70,83,158,203,etude
15,Luxembourg,6,5,6,13,14,7,35,60,62,83,etude
16,Hongrie,79,116,87,35,25,9,15,21,25,46,etude
17,Malte,13,22,8,27,5,3,0,6,68,69,etude
18,Pays-Bas,22,23,29,34,36,41,41,39,40,35,etude
19,Autriche,4,2,0,1,3,2,4,5,12,7,etude
20,Pologne,20,26,28,37,34,47,57,45,29,15,etude
21,Portugal,8,25,3,10,11,10,15,5,13,12,etude
22,Roumanie,12,19,27,60,59,49,44,44,24,19,etude
23,Slovénie,0,1,0,0,0,0,0,1,1,4,etude
24,Slovaquie,0,1,1,2,1,0,0,0,0,1,etude
25,Finlande,44,34,30,16,9,41,49,95,166,70,etude
26,Suède,24,15,37,73,112,110,61,31,22,30,etude
27,Islande,0,2,1,0,1,2,0,1,3,4,etude
28,Liechtenstein,0,1,1,1,0,0,0,0,0,2,etude
29,Norvège,24,28,42,33,37,16,15,10,8,4,etude
30,Suisse,37,39,30,30,24,33,32,49,48,75,etude
31,United Kingdom,216,171,145,124,0,0,0,0,0,0,etude
32,Serbie,0,0,0,0,0,0,0,0,0,1,etude

In [64]:
def reshape_first_permits_long(df):
    df_long = df.melt(
        id_vars=["destination_country", "motif"],
        var_name="year",
        value_name="permits"
    )

    df_long["year"] = df_long["year"].astype(int)
    df_long["permits"] = (
        pd.to_numeric(df_long["permits"], errors="coerce")
        .fillna(0)
        .astype(int)
    )

    df_long = df_long[
        ["destination_country", "motif", "year", "permits"]
    ]

    return df_long

In [65]:
sheet2_raw = reshape_first_permits_long(sheet2_raw)
sheet2_raw

    destination_country  motif  year  permits
0              Belgique  etude  2015      652
1              Bulgarie  etude  2015        4
2              Tchéquie  etude  2015       10
3              Danemark  etude  2015       40
4             Allemagne  etude  2015      526
..                  ...    ...   ...      ...
325       Liechtenstein  etude  2024        2
326             Norvège  etude  2024        4
327              Suisse  etude  2024       75
328      United Kingdom  etude  2024        0
329              Serbie  etude  2024        1

[330 rows x 4 columns]

In [66]:
def clean_and_reshape_first_permits(excel_path, sheet_name, motif):
    df = pd.read_excel(
        excel_path,
        sheet_name=sheet_name,
        header=None
    )

    # Supprimer les colonnes 2, 4, 6, ..., 20
    df = df.drop(
        columns=list(range(2, 21, 2)),
        errors="ignore"
    )

    # Supprimer les lignes inutiles
    rows_to_drop = list(range(0, 10)) + [11, 12, 13] + list(range(47, 53))

    df = df.drop(
        index=rows_to_drop,
        errors="ignore"
    )

    # Remplacer les ":" par 0
    df = df.replace(":", 0)

    # Mettre la ligne 10 comme entête
    df.columns = df.iloc[0]
    df = df.iloc[1:].reset_index(drop=True)

    # Renommer TIME en destination_country
    df = df.rename(columns={"TIME": "destination_country"})

    # Ajouter le motif
    df["motif"] = motif

    # Passer au format long
    df = df.melt(
        id_vars=["destination_country", "motif"],
        var_name="year",
        value_name="permits"
    )

    # Nettoyer les types
    df["year"] = df["year"].astype(int)

    df["permits"] = (
        pd.to_numeric(df["permits"], errors="coerce")
        .fillna(0)
        .astype(int)
    )

    # Réordonner les colonnes
    df = df[
        ["destination_country", "motif", "year", "permits"]
    ]

    return df

In [67]:
sheet3_raw = clean_and_reshape_first_permits(
    EUROPE_PATH / "eurostat_first_permits_cameroon.xlsx",
    sheet_name="Feuille 3",
    motif="travail"
)

sheet3_raw

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

    destination_country    motif  year  permits
0              Belgique  travail  2015       48
1              Bulgarie  travail  2015        0
2              Tchéquie  travail  2015        3
3              Danemark  travail  2015       39
4             Allemagne  travail  2015       69
..                  ...      ...   ...      ...
325       Liechtenstein  travail  2024        0
326             Norvège  travail  2024        4
327              Suisse  travail  2024       19
328      United Kingdom  travail  2024        0
329              Serbie  travail  2024        7

[330 rows x 4 columns]

In [68]:
sheet4_raw = clean_and_reshape_first_permits(
    EUROPE_PATH / "eurostat_first_permits_cameroon.xlsx",
    sheet_name="Feuille 4",
    motif="autre"
)

sheet4_raw

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

    destination_country  motif  year  permits
0              Belgique  autre  2015      179
1              Bulgarie  autre  2015        0
2              Tchéquie  autre  2015        1
3              Danemark  autre  2015        3
4             Allemagne  autre  2015       71
..                  ...    ...   ...      ...
325       Liechtenstein  autre  2024        0
326             Norvège  autre  2024        5
327              Suisse  autre  2024       23
328      United Kingdom  autre  2024        0
329              Serbie  autre  2024        0

[330 rows x 4 columns]

In [69]:
eurostat_first_permits_cleaned = pd.concat(
    [sheet1_raw, sheet2_raw, sheet3_raw, sheet4_raw],
    ignore_index=True
)

eurostat_first_permits_cleaned

     destination_country    motif  year  permits
0               Belgique  famille  2015      695
1               Bulgarie  famille  2015        0
2               Tchéquie  famille  2015       15
3               Danemark  famille  2015       55
4              Allemagne  famille  2015      748
...                  ...      ...   ...      ...
1315       Liechtenstein    autre  2024        0
1316             Norvège    autre  2024        5
1317              Suisse    autre  2024       23
1318      United Kingdom    autre  2024        0
1319              Serbie    autre  2024        0

[1320 rows x 4 columns]

In [70]:
eurostat_first_permits_cleaned["source"] = "eurostat"

eurostat_first_permits_cleaned

     destination_country    motif  year  permits    source
0               Belgique  famille  2015      695  eurostat
1               Bulgarie  famille  2015        0  eurostat
2               Tchéquie  famille  2015       15  eurostat
3               Danemark  famille  2015       55  eurostat
4              Allemagne  famille  2015      748  eurostat
...                  ...      ...   ...      ...       ...
1315       Liechtenstein    autre  2024        0  eurostat
1316             Norvège    autre  2024        5  eurostat
1317              Suisse    autre  2024       23  eurostat
1318      United Kingdom    autre  2024        0  eurostat
1319              Serbie    autre  2024        0  eurostat

[1320 rows x 5 columns]

In [71]:
eurostat_first_permits_cleaned.to_csv(
    CLEANED_PATH / "eurostat_first_permits_cleaned.csv",
    index=False
)

In [72]:
eurostat_first_permits_cleaned = eurostat_first_permits_cleaned.rename(
    columns={"motif": "entry_reasons"}
)

eurostat_first_permits_cleaned

     destination_country entry_reasons  year  permits    source
0               Belgique       famille  2015      695  eurostat
1               Bulgarie       famille  2015        0  eurostat
2               Tchéquie       famille  2015       15  eurostat
3               Danemark       famille  2015       55  eurostat
4              Allemagne       famille  2015      748  eurostat
...                  ...           ...   ...      ...       ...
1315       Liechtenstein         autre  2024        0  eurostat
1316             Norvège         autre  2024        5  eurostat
1317              Suisse         autre  2024       23  eurostat
1318      United Kingdom         autre  2024        0  eurostat
1319              Serbie         autre  2024        0  eurostat

[1320 rows x 5 columns]

In [73]:
eurostat_first_permits_cleaned.to_csv(
    CLEANED_PATH / "eurostat_first_permits_cleaned.csv",
    index=False
)