## Nettoyage - Eurostat résidents de longue durée - Cameroun

In [1]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("..")
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

EUROPE_PATH = DATA_RAW / "europe"
CLEANED_PATH = DATA_PROCESSED / "cleaned"

CLEANED_PATH.mkdir(parents=True, exist_ok=True)

In [2]:
xls = pd.ExcelFile(EUROPE_PATH / "eurostat_long_term_residents_cameroon.xlsx")
xls.sheet_names

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

['Summary', 'Sheet 1', 'Sheet 2', 'Sheet 3']

In [4]:
sheet1_raw = pd.read_excel(
    EUROPE_PATH / "eurostat_long_term_residents_cameroon.xlsx",
    sheet_name="Sheet 1",
    header=None
)

sheet1_raw

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Data extracted on 09/04/2026 14:04:03 from [ES...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dataset:,Long-term residents by citizenship on 31 Decem...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Last updated:,23/03/2026 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Time frequency,NaN,Annual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Legal framework,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Country of citizenship,NaN,Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Unit of measure,NaN,Person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,TIME,2015,NaN,2016,NaN,2017,NaN,2018,NaN,2019,...,2020,NaN,2021,NaN,2022,NaN,2023,NaN,2024,NaN
10,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,European Union - 27 countries (from 2020),40523,NaN,47511,NaN,49796,NaN,:,NaN,51601,...,52523,NaN,53111,NaN,59455,NaN,61734,NaN,63999,NaN
12,European Union - 28 countries (2013-2020),45370,NaN,52358,NaN,54643,NaN,:,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
13,Belgium,977,NaN,2943,b,2834,NaN,2802,NaN,2879,...,3058,NaN,3287,NaN,6719,NaN,7020,NaN,7570,NaN
14,Bulgaria,6,NaN,6,NaN,11,NaN,11,NaN,12,...,12,NaN,12,NaN,13,NaN,15,NaN,16,NaN
15,Czechia,53,NaN,56,NaN,58,NaN,59,NaN,60,...,62,NaN,70,NaN,73,NaN,79,NaN,80,NaN
16,Denmark,121,NaN,109,NaN,95,NaN,97,NaN,146,...,158,NaN,179,NaN,197,NaN,227,NaN,229,NaN
17,Germany,80,NaN,2456,b,2565,NaN,2722,NaN,2959,...,3068,NaN,2934,NaN,3533,NaN,4147,NaN,4277,NaN
18,Estonia,0,NaN,0,NaN,0,NaN,1,NaN,2,...,1,NaN,1,NaN,1,NaN,3,NaN,5,NaN
19,Ireland,0,NaN,0,NaN,0,NaN,0,NaN,0,...,0,NaN,0,u,1,u,1,u,1,u
20,Greece,15,NaN,17,NaN,22,NaN,25,NaN,25,...,27,NaN,25,NaN,13,NaN,16,NaN,17,NaN
21,Spain,2176,NaN,4148,b,4314,NaN,4479,NaN,4553,...,4463,NaN,4286,NaN,4629,NaN,4678,NaN,4746,NaN
22,France,28272,NaN,29220,NaN,30889,NaN,31078,NaN,32009,...,32924,NaN,33707,p,34783,NaN,36195,NaN,37897,NaN
23,Croatia,7,NaN,7,NaN,7,NaN,8,NaN,8,...,8,NaN,7,NaN,7,NaN,7,NaN,13,NaN
24,Italy,7694,NaN,7333,NaN,7594,NaN,7277,NaN,7277,...,6982,NaN,6889,NaN,7795,NaN,7684,NaN,7406,NaN
25,Cyprus,0,NaN,0,NaN,0,NaN,1,NaN,10,...,9,NaN,7,NaN,7,NaN,7,NaN,6,NaN
26,Latvia,0,NaN,0,NaN,0,NaN,0,NaN,0,...,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN
27,Lithuania,0,NaN,0,NaN,0,NaN,:,NaN,3,...,4,NaN,5,NaN,5,NaN,11,NaN,25,NaN
28,Luxembourg,104,NaN,127,NaN,146,NaN,172,NaN,203,...,237,NaN,192,NaN,232,NaN,247,NaN,276,NaN
29,Hungary,4,NaN,7,NaN,114,b,118,NaN,120,...,111,NaN,111,NaN,95,NaN,59,NaN,57,NaN
30,Malta,1,NaN,1,NaN,1,NaN,1,NaN,1,...,1,NaN,2,NaN,3,NaN,3,NaN,5,NaN
31,Netherlands,70,NaN,75,NaN,79,NaN,93,NaN,107,...,94,NaN,91,NaN,94,NaN,87,NaN,91,NaN
32,Austria,59,NaN,79,NaN,89,NaN,97,NaN,110,...,121,NaN,125,NaN,138,NaN,148,NaN,156,NaN
33,Poland,123,NaN,121,NaN,128,NaN,140,NaN,116,...,140,NaN,136,NaN,126,NaN,117,NaN,87,NaN
34,Portugal,0,NaN,0,NaN,7,NaN,23,NaN,22,...,23,NaN,22,NaN,21,NaN,17,NaN,32,NaN
35,Romania,5,NaN,8,NaN,14,NaN,19,NaN,23,...,23,NaN,25,NaN,23,NaN,29,NaN,36,NaN
36,Slovenia,0,NaN,0,NaN,0,NaN,0,NaN,8,...,10,NaN,11,NaN,10,NaN,12,NaN,14,NaN
37,Slovakia,8,NaN,8,NaN,10,NaN,12,NaN,16,...,17,NaN,18,NaN,14,NaN,14,NaN,13,NaN
38,Finland,193,NaN,206,NaN,227,NaN,264,NaN,286,...,324,NaN,368,NaN,417,NaN,474,NaN,529,NaN
39,Sweden,555,b,584,NaN,592,NaN,585,NaN,646,...,646,NaN,601,NaN,506,NaN,437,NaN,415,NaN
40,Iceland,2,NaN,2,NaN,2,NaN,2,NaN,2,...,3,NaN,2,NaN,2,NaN,2,NaN,2,NaN
41,Liechtenstein,2,NaN,2,NaN,0,NaN,0,NaN,0,...,0,NaN,0,NaN,0,NaN,4,NaN,4,NaN
42,Norway,79,NaN,71,NaN,63,NaN,81,NaN,75,...,75,NaN,67,NaN,60,NaN,45,NaN,49,NaN
43,Switzerland,2124,NaN,2188,NaN,2238,NaN,:,NaN,:,...,2358,NaN,2447,NaN,2473,NaN,2502,NaN,2528,NaN
44,United Kingdom,4847,NaN,4847,b,4847,NaN,5362,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,:,NaN
45,Serbia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,:,NaN,:,NaN,:,NaN,:,NaN,7,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Special value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,:,not available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Observation flags:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,b,break in time series,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,p,provisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,u,low reliability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
sheet1_raw = sheet1_raw.drop(
    columns=list(range(2, 21, 2)),
    errors="ignore"
)

sheet1_raw = sheet1_raw.drop(
    index=list(range(0, 9)) + list(range(46, 52)),
    errors="ignore"
)

sheet1_raw = sheet1_raw.reset_index(drop=True)

sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,European Union - 27 countries (from 2020),40523,47511,49796,:,51601,52523,53111,59455,61734,63999
3,European Union - 28 countries (2013-2020),45370,52358,54643,:,:,:,:,:,:,:
4,Belgium,977,2943,2834,2802,2879,3058,3287,6719,7020,7570
5,Bulgaria,6,6,11,11,12,12,12,13,15,16
6,Czechia,53,56,58,59,60,62,70,73,79,80
7,Denmark,121,109,95,97,146,158,179,197,227,229
8,Germany,80,2456,2565,2722,2959,3068,2934,3533,4147,4277
9,Estonia,0,0,0,1,2,1,1,1,3,5
10,Ireland,0,0,0,0,0,0,0,1,1,1
11,Greece,15,17,22,25,25,27,25,13,16,17
12,Spain,2176,4148,4314,4479,4553,4463,4286,4629,4678,4746
13,France,28272,29220,30889,31078,32009,32924,33707,34783,36195,37897
14,Croatia,7,7,7,8,8,8,7,7,7,13
15,Italy,7694,7333,7594,7277,7277,6982,6889,7795,7684,7406
16,Cyprus,0,0,0,1,10,9,7,7,7,6
17,Latvia,0,0,0,0,0,0,0,0,0,0
18,Lithuania,0,0,0,:,3,4,5,5,11,25
19,Luxembourg,104,127,146,172,203,237,192,232,247,276
20,Hungary,4,7,114,118,120,111,111,95,59,57
21,Malta,1,1,1,1,1,1,2,3,3,5
22,Netherlands,70,75,79,93,107,94,91,94,87,91
23,Austria,59,79,89,97,110,121,125,138,148,156
24,Poland,123,121,128,140,116,140,136,126,117,87
25,Portugal,0,0,7,23,22,23,22,21,17,32
26,Romania,5,8,14,19,23,23,25,23,29,36
27,Slovenia,0,0,0,0,8,10,11,10,12,14
28,Slovakia,8,8,10,12,16,17,18,14,14,13
29,Finland,193,206,227,264,286,324,368,417,474,529
30,Sweden,555,584,592,585,646,646,601,506,437,415
31,Iceland,2,2,2,2,2,3,2,2,2,2
32,Liechtenstein,2,2,0,0,0,0,0,0,4,4
33,Norway,79,71,63,81,75,75,67,60,45,49
34,Switzerland,2124,2188,2238,:,:,2358,2447,2473,2502,2528
35,United Kingdom,4847,4847,4847,5362,:,:,:,:,:,:
36,Serbia,:,:,:,:,:,:,:,:,:,7
37,u,low reliability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
sheet1_raw = sheet1_raw.drop(index=[1, 2, 3, 37], errors="ignore").reset_index(drop=True)
sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Belgium,977,2943,2834,2802,2879,3058,3287,6719,7020,7570
2,Bulgaria,6,6,11,11,12,12,12,13,15,16
3,Czechia,53,56,58,59,60,62,70,73,79,80
4,Denmark,121,109,95,97,146,158,179,197,227,229
5,Germany,80,2456,2565,2722,2959,3068,2934,3533,4147,4277
6,Estonia,0,0,0,1,2,1,1,1,3,5
7,Ireland,0,0,0,0,0,0,0,1,1,1
8,Greece,15,17,22,25,25,27,25,13,16,17
9,Spain,2176,4148,4314,4479,4553,4463,4286,4629,4678,4746
10,France,28272,29220,30889,31078,32009,32924,33707,34783,36195,37897
11,Croatia,7,7,7,8,8,8,7,7,7,13
12,Italy,7694,7333,7594,7277,7277,6982,6889,7795,7684,7406
13,Cyprus,0,0,0,1,10,9,7,7,7,6
14,Latvia,0,0,0,0,0,0,0,0,0,0
15,Lithuania,0,0,0,:,3,4,5,5,11,25
16,Luxembourg,104,127,146,172,203,237,192,232,247,276
17,Hungary,4,7,114,118,120,111,111,95,59,57
18,Malta,1,1,1,1,1,1,2,3,3,5
19,Netherlands,70,75,79,93,107,94,91,94,87,91
20,Austria,59,79,89,97,110,121,125,138,148,156
21,Poland,123,121,128,140,116,140,136,126,117,87
22,Portugal,0,0,7,23,22,23,22,21,17,32
23,Romania,5,8,14,19,23,23,25,23,29,36
24,Slovenia,0,0,0,0,8,10,11,10,12,14
25,Slovakia,8,8,10,12,16,17,18,14,14,13
26,Finland,193,206,227,264,286,324,368,417,474,529
27,Sweden,555,584,592,585,646,646,601,506,437,415
28,Iceland,2,2,2,2,2,3,2,2,2,2
29,Liechtenstein,2,2,0,0,0,0,0,0,4,4
30,Norway,79,71,63,81,75,75,67,60,45,49
31,Switzerland,2124,2188,2238,:,:,2358,2447,2473,2502,2528
32,United Kingdom,4847,4847,4847,5362,:,:,:,:,:,:
33,Serbia,:,:,:,:,:,:,:,:,:,7

In [9]:
sheet1_raw = sheet1_raw.replace(":", 0)
sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Belgium,977,2943,2834,2802,2879,3058,3287,6719,7020,7570
2,Bulgaria,6,6,11,11,12,12,12,13,15,16
3,Czechia,53,56,58,59,60,62,70,73,79,80
4,Denmark,121,109,95,97,146,158,179,197,227,229
5,Germany,80,2456,2565,2722,2959,3068,2934,3533,4147,4277
6,Estonia,0,0,0,1,2,1,1,1,3,5
7,Ireland,0,0,0,0,0,0,0,1,1,1
8,Greece,15,17,22,25,25,27,25,13,16,17
9,Spain,2176,4148,4314,4479,4553,4463,4286,4629,4678,4746
10,France,28272,29220,30889,31078,32009,32924,33707,34783,36195,37897
11,Croatia,7,7,7,8,8,8,7,7,7,13
12,Italy,7694,7333,7594,7277,7277,6982,6889,7795,7684,7406
13,Cyprus,0,0,0,1,10,9,7,7,7,6
14,Latvia,0,0,0,0,0,0,0,0,0,0
15,Lithuania,0,0,0,0,3,4,5,5,11,25
16,Luxembourg,104,127,146,172,203,237,192,232,247,276
17,Hungary,4,7,114,118,120,111,111,95,59,57
18,Malta,1,1,1,1,1,1,2,3,3,5
19,Netherlands,70,75,79,93,107,94,91,94,87,91
20,Austria,59,79,89,97,110,121,125,138,148,156
21,Poland,123,121,128,140,116,140,136,126,117,87
22,Portugal,0,0,7,23,22,23,22,21,17,32
23,Romania,5,8,14,19,23,23,25,23,29,36
24,Slovenia,0,0,0,0,8,10,11,10,12,14
25,Slovakia,8,8,10,12,16,17,18,14,14,13
26,Finland,193,206,227,264,286,324,368,417,474,529
27,Sweden,555,584,592,585,646,646,601,506,437,415
28,Iceland,2,2,2,2,2,3,2,2,2,2
29,Liechtenstein,2,2,0,0,0,0,0,0,4,4
30,Norway,79,71,63,81,75,75,67,60,45,49
31,Switzerland,2124,2188,2238,0,0,2358,2447,2473,2502,2528
32,United Kingdom,4847,4847,4847,5362,0,0,0,0,0,0
33,Serbia,0,0,0,0,0,0,0,0,0,7

In [ ]:
# Mettre la première ligne comme entête
sheet1_raw.columns = sheet1_raw.iloc[0]
sheet1_raw = sheet1_raw.iloc[1:].reset_index(drop=True)

# Renommer TIME en destination_country
sheet1_raw = sheet1_raw.rename(
    columns={"TIME": "destination_country"}
)

# Passer du format large au format long
sheet1_raw = sheet1_raw.melt(
    id_vars=["destination_country"],
    var_name="year",
    value_name="residents"
)

# Nettoyer les types
sheet1_raw["year"] = sheet1_raw["year"].astype(int)

sheet1_raw["residents"] = (
    pd.to_numeric(sheet1_raw["residents"], errors="coerce")
    .fillna(0)
    .astype(int)
)

# Réordonner les colonnes
sheet1_raw = sheet1_raw[
    ["destination_country", "year", "residents"]
]

sheet1_raw

    destination_country  year  residents
0               Belgium  2015        977
1              Bulgaria  2015          6
2               Czechia  2015         53
3               Denmark  2015        121
4               Germany  2015         80
..                  ...   ...        ...
325       Liechtenstein  2024          4
326              Norway  2024         49
327         Switzerland  2024       2528
328      United Kingdom  2024          0
329              Serbia  2024          7

[330 rows x 3 columns]

In [12]:
sheet1_raw["source"] = "eurostat"
sheet1_raw["nature"] = "long_term_resident"

def classify_covid_period(year):
    if year < 2020:
        return "pre_covid"
    elif year in [2020, 2021]:
        return "covid"
    else:
        return "post_covid"

sheet1_raw["covid_period"] = sheet1_raw["year"].apply(classify_covid_period)

sheet1_raw

,destination_country,year,residents,source,nature,covid_period
0,Belgium,2015,977,eurostat,long_term_resident,pre_covid
1,Bulgaria,2015,6,eurostat,long_term_resident,pre_covid
2,Czechia,2015,53,eurostat,long_term_resident,pre_covid
3,Denmark,2015,121,eurostat,long_term_resident,pre_covid
4,Germany,2015,80,eurostat,long_term_resident,pre_covid
...,...,...,...,...,...,...
325,Liechtenstein,2024,4,eurostat,long_term_resident,post_covid
326,Norway,2024,49,eurostat,long_term_resident,post_covid
327,Switzerland,2024,2528,eurostat,long_term_resident,post_covid
328,United Kingdom,2024,0,eurostat,long_term_resident,post_covid
329,Serbia,2024,7,eurostat,long_term_resident,post_covid

In [15]:
sheet1_raw = sheet1_raw.rename(
    columns={"permit": "permits"}
)

sheet1_raw

,destination_country,year,permits,source,nature,covid_period
0,Belgium,2015,977,eurostat,long_term_resident,pre_covid
1,Bulgaria,2015,6,eurostat,long_term_resident,pre_covid
2,Czechia,2015,53,eurostat,long_term_resident,pre_covid
3,Denmark,2015,121,eurostat,long_term_resident,pre_covid
4,Germany,2015,80,eurostat,long_term_resident,pre_covid
...,...,...,...,...,...,...
325,Liechtenstein,2024,4,eurostat,long_term_resident,post_covid
326,Norway,2024,49,eurostat,long_term_resident,post_covid
327,Switzerland,2024,2528,eurostat,long_term_resident,post_covid
328,United Kingdom,2024,0,eurostat,long_term_resident,post_covid
329,Serbia,2024,7,eurostat,long_term_resident,post_covid

In [16]:
sheet1_raw.to_csv(
    CLEANED_PATH / "eurostat_long_term_residents_cleaned.csv",
    index=False
)