## Cleaning - Eurostat long term residents Cameroon

In [1]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("..")
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

EUROPE_PATH = DATA_RAW / "europe"
CLEANED_PATH = DATA_PROCESSED / "cleaned"

CLEANED_PATH.mkdir(parents=True, exist_ok=True)

In [2]:
xls = pd.ExcelFile(EUROPE_PATH / "eurostat_status_changes_cameroon.xlsx")
xls.sheet_names

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

['Summary',
 'Sheet 1',
 'Sheet 2',
 'Sheet 3',
 'Sheet 4',
 'Sheet 5',
 'Sheet 6',
 'Sheet 7',
 'Sheet 8',
 'Sheet 9',
 'Sheet 10',
 'Sheet 11',
 'Sheet 12',
 'Sheet 13',
 'Sheet 14',
 'Sheet 15',
 'Sheet 16',
 'Sheet 17',
 'Sheet 18',
 'Sheet 19',
 'Sheet 20',
 'Sheet 21',
 'Sheet 22',
 'Sheet 23',
 'Sheet 24',
 'Sheet 25',
 'Sheet 26',
 'Sheet 27',
 'Sheet 28',
 'Sheet 29',
 'Sheet 30',
 'Sheet 31',
 'Sheet 32',
 'Sheet 33',
 'Sheet 34',
 'Sheet 35',
 'Sheet 36',
 'Sheet 37',
 'Sheet 38',
 'Sheet 39',
 'Sheet 40',
 'Sheet 41',
 'Sheet 42',
 'Sheet 43',
 'Sheet 44',
 'Sheet 45',
 'Sheet 46',
 'Sheet 47',
 'Sheet 48',
 'Sheet 49',
 'Sheet 50',
 'Sheet 51',
 'Sheet 52',
 'Sheet 53',
 'Sheet 54',
 'Sheet 55',
 'Sheet 56',
 'Sheet 57',
 'Sheet 58',
 'Sheet 59',
 'Sheet 60',
 'Sheet 61',
 'Sheet 62',
 'Sheet 63',
 'Sheet 64',
 'Sheet 65',
 'Sheet 66',
 'Sheet 67',
 'Sheet 68',
 'Sheet 69',
 'Sheet 70',
 'Sheet 71',
 'Sheet 72',
 'Sheet 73',
 'Sheet 74',
 'Sheet 75',
 'Sheet 76',
 'Sheet 77',
 'Sheet 78',
 'Sheet 79',
 'Sheet 80',
 'Sheet 81',
 'Sheet 82',
 'Sheet 83',
 'Sheet 84',
 'Sheet 85',
 'Sheet 86',
 'Sheet 87',
 'Sheet 88',
 'Sheet 89',
 'Sheet 90',
 'Sheet 91',
 'Sheet 92',
 'Sheet 93',
 'Sheet 94',
 'Sheet 95',
 'Sheet 96']

In [3]:
sheet1_raw = pd.read_excel(
    EUROPE_PATH / "eurostat_status_changes_cameroon.xlsx",
    sheet_name="Sheet 1",
    header=None
)

sheet1_raw

,0,1,2,3,4,5,6,7,8,9,10
0,Data extracted on 09/04/2026 14:05:58 from [ES...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dataset:,"Change of immigration status permits by age, s...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Last updated:,23/03/2026 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Time frequency,NaN,Annual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Country of citizenship,NaN,Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Age class,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Sex,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Unit of measure,NaN,Person,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,TIME,2020,NaN,2021,NaN,2022,NaN,2023,NaN,2024.0,NaN
11,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,European Union - 27 countries (from 2020),:,NaN,:,NaN,:,NaN,:,NaN,6696.0,NaN
13,Belgium,:,NaN,426,NaN,504,NaN,656,NaN,548.0,NaN
14,Bulgaria,:,NaN,0,NaN,1,NaN,0,NaN,1.0,NaN
15,Czechia,:,NaN,3,NaN,8,NaN,16,NaN,10.0,NaN
16,Denmark,:,NaN,14,NaN,35,NaN,14,NaN,10.0,NaN
17,Germany,:,NaN,236,NaN,517,NaN,585,NaN,496.0,NaN
18,Estonia,:,NaN,15,NaN,13,NaN,4,NaN,5.0,NaN
19,Ireland,:,NaN,9,u,67,u,14,u,24.0,u
20,Greece,:,NaN,6,NaN,1,NaN,5,NaN,3.0,NaN
21,Spain,:,NaN,109,NaN,145,NaN,170,NaN,138.0,NaN
22,France,2410,NaN,3016,NaN,3359,NaN,4130,NaN,5007.0,NaN
23,Croatia,:,NaN,3,NaN,2,NaN,1,NaN,2.0,NaN
24,Italy,:,NaN,237,NaN,273,NaN,294,NaN,229.0,NaN
25,Cyprus,:,NaN,0,NaN,0,NaN,1,NaN,2.0,NaN
26,Latvia,:,NaN,6,NaN,10,NaN,11,NaN,12.0,NaN
27,Lithuania,:,NaN,41,NaN,76,NaN,42,NaN,1.0,NaN
28,Luxembourg,:,NaN,27,NaN,35,NaN,26,NaN,44.0,NaN
29,Hungary,:,NaN,6,NaN,7,NaN,7,NaN,0.0,NaN
30,Malta,:,NaN,:,NaN,:,NaN,:,NaN,5.0,NaN
31,Netherlands,:,NaN,17,NaN,25,NaN,24,NaN,11.0,NaN
32,Austria,:,NaN,0,NaN,0,NaN,1,NaN,4.0,NaN
33,Poland,:,NaN,4,NaN,0,NaN,26,NaN,15.0,NaN
34,Portugal,:,NaN,7,NaN,5,NaN,2,NaN,1.0,NaN
35,Romania,:,NaN,7,NaN,12,NaN,17,NaN,12.0,NaN
36,Slovenia,:,NaN,0,NaN,1,NaN,0,NaN,2.0,NaN
37,Slovakia,:,NaN,:,NaN,:,NaN,:,NaN,1.0,NaN
38,Finland,36,NaN,28,NaN,30,NaN,48,NaN,94.0,NaN
39,Sweden,24,NaN,28,NaN,32,NaN,30,NaN,19.0,NaN
40,Iceland,1,NaN,0,NaN,0,NaN,0,NaN,1.0,NaN
41,Liechtenstein,:,NaN,0,NaN,0,NaN,1,NaN,1.0,NaN
42,Norway,:,NaN,13,NaN,8,NaN,6,NaN,4.0,NaN
43,Serbia,:,NaN,:,NaN,:,NaN,:,NaN,0.0,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Special value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,:,not available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Observation flags:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,u,low reliability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
sheet1_raw = sheet1_raw.drop(columns=[2, 4, 6, 8, 10], errors="ignore")
sheet1_raw = sheet1_raw.drop(index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 44, 45, 46, 47, 48], errors="ignore").reset_index(drop=True)

sheet1_raw

                                            0     1     3     5     7       9
0                                        TIME  2020  2021  2022  2023  2024.0
1                                GEO (Labels)   NaN   NaN   NaN   NaN     NaN
2   European Union - 27 countries (from 2020)     :     :     :     :  6696.0
3                                     Belgium     :   426   504   656   548.0
4                                    Bulgaria     :     0     1     0     1.0
5                                     Czechia     :     3     8    16    10.0
6                                     Denmark     :    14    35    14    10.0
7                                     Germany     :   236   517   585   496.0
8                                     Estonia     :    15    13     4     5.0
9                                     Ireland     :     9    67    14    24.0
10                                     Greece     :     6     1     5     3.0
11                                      Spain     :   109   145   170   138.0
12                                     France  2410  3016  3359  4130  5007.0
13                                    Croatia     :     3     2     1     2.0
14                                      Italy     :   237   273   294   229.0
15                                     Cyprus     :     0     0     1     2.0
16                                     Latvia     :     6    10    11    12.0
17                                  Lithuania     :    41    76    42     1.0
18                                 Luxembourg     :    27    35    26    44.0
19                                    Hungary     :     6     7     7     0.0
20                                      Malta     :     :     :     :     5.0
21                                Netherlands     :    17    25    24    11.0
22                                    Austria     :     0     0     1     4.0
23                                     Poland     :     4     0    26    15.0
24                                   Portugal     :     7     5     2     1.0
25                                    Romania     :     7    12    17    12.0
26                                   Slovenia     :     0     1     0     2.0
27                                   Slovakia     :     :     :     :     1.0
28                                    Finland    36    28    30    48    94.0
29                                     Sweden    24    28    32    30    19.0
30                                    Iceland     1     0     0     0     1.0
31                              Liechtenstein     :     0     0     1     1.0
32                                     Norway     :    13     8     6     4.0
33                                     Serbia     :     :     :     :     0.0

In [5]:
sheet1_raw = sheet1_raw.replace(":", 0)
sheet1_raw = sheet1_raw.rename(
    columns={"TIME": "destination_country"}
)
sheet1_raw = sheet1_raw.drop(index=[1, 2])

sheet1_raw

                0     1     3     5     7       9
0            TIME  2020  2021  2022  2023  2024.0
3         Belgium     0   426   504   656   548.0
4        Bulgaria     0     0     1     0     1.0
5         Czechia     0     3     8    16    10.0
6         Denmark     0    14    35    14    10.0
7         Germany     0   236   517   585   496.0
8         Estonia     0    15    13     4     5.0
9         Ireland     0     9    67    14    24.0
10         Greece     0     6     1     5     3.0
11          Spain     0   109   145   170   138.0
12         France  2410  3016  3359  4130  5007.0
13        Croatia     0     3     2     1     2.0
14          Italy     0   237   273   294   229.0
15         Cyprus     0     0     0     1     2.0
16         Latvia     0     6    10    11    12.0
17      Lithuania     0    41    76    42     1.0
18     Luxembourg     0    27    35    26    44.0
19        Hungary     0     6     7     7     0.0
20          Malta     0     0     0     0     5.0
21    Netherlands     0    17    25    24    11.0
22        Austria     0     0     0     1     4.0
23         Poland     0     4     0    26    15.0
24       Portugal     0     7     5     2     1.0
25        Romania     0     7    12    17    12.0
26       Slovenia     0     0     1     0     2.0
27       Slovakia     0     0     0     0     1.0
28        Finland    36    28    30    48    94.0
29         Sweden    24    28    32    30    19.0
30        Iceland     1     0     0     0     1.0
31  Liechtenstein     0     0     0     1     1.0
32         Norway     0    13     8     6     4.0
33         Serbia     0     0     0     0     0.0

In [6]:
# Mettre la première ligne comme entête
sheet1_raw.columns = sheet1_raw.iloc[0]
sheet1_raw = sheet1_raw.iloc[1:].reset_index(drop=True)

# Renommer TIME en destination_country
sheet1_raw = sheet1_raw.rename(
    columns={"TIME": "destination_country"}
)

# Supprimer la ligne GEO (Labels) si elle existe encore
sheet1_raw = sheet1_raw[
    sheet1_raw["destination_country"] != "GEO (Labels)"
]

# Passer du format large au format long
sheet1_raw = sheet1_raw.melt(
    id_vars=["destination_country"],
    var_name="year",
    value_name="permit"
)

# Nettoyer les types
sheet1_raw["year"] = sheet1_raw["year"].astype(int)

sheet1_raw["permit"] = (
    pd.to_numeric(sheet1_raw["permit"], errors="coerce")
    .fillna(0)
    .astype(int)
)

# Réordonner les colonnes
sheet1_raw = sheet1_raw[
    ["destination_country", "year", "permit"]
]

sheet1_raw

    destination_country  year  permit
0               Belgium  2020       0
1              Bulgaria  2020       0
2               Czechia  2020       0
3               Denmark  2020       0
4               Germany  2020       0
..                  ...   ...     ...
150              Sweden  2024      19
151             Iceland  2024       1
152       Liechtenstein  2024       1
153              Norway  2024       4
154              Serbia  2024       0

[155 rows x 3 columns]

In [7]:
# Renommer permit en permits
sheet1_raw = sheet1_raw.rename(
    columns={"permit": "permits"}
)

In [8]:
# Ajouter les colonnes source et nature
sheet1_raw["source"] = "eurostat"
sheet1_raw["nature"] = "status_change"

# Ajouter la période Covid
def classify_covid_period(year):
    if year < 2020:
        return "pre_covid"
    elif year in [2020, 2021]:
        return "covid"
    else:
        return "post_covid"

sheet1_raw["period_covid"] = sheet1_raw["year"].apply(classify_covid_period)

# Réordonner les colonnes
sheet1_raw = sheet1_raw[
    [
        "destination_country",
        "year",
        "permits",
        "source",
        "nature",
        "period_covid"
    ]
]

sheet1_raw

    destination_country  year  permits    source         nature period_covid
0               Belgium  2020        0  eurostat  status_change        covid
1              Bulgaria  2020        0  eurostat  status_change        covid
2               Czechia  2020        0  eurostat  status_change        covid
3               Denmark  2020        0  eurostat  status_change        covid
4               Germany  2020        0  eurostat  status_change        covid
..                  ...   ...      ...       ...            ...          ...
150              Sweden  2024       19  eurostat  status_change   post_covid
151             Iceland  2024        1  eurostat  status_change   post_covid
152       Liechtenstein  2024        1  eurostat  status_change   post_covid
153              Norway  2024        4  eurostat  status_change   post_covid
154              Serbia  2024        0  eurostat  status_change   post_covid

[155 rows x 6 columns]

In [9]:
sheet1_raw = sheet1_raw.rename(
    columns={"period_covid": "covid_period"}
)

sheet1_raw

    destination_country  year  permits    source         nature covid_period
0               Belgium  2020        0  eurostat  status_change        covid
1              Bulgaria  2020        0  eurostat  status_change        covid
2               Czechia  2020        0  eurostat  status_change        covid
3               Denmark  2020        0  eurostat  status_change        covid
4               Germany  2020        0  eurostat  status_change        covid
..                  ...   ...      ...       ...            ...          ...
150              Sweden  2024       19  eurostat  status_change   post_covid
151             Iceland  2024        1  eurostat  status_change   post_covid
152       Liechtenstein  2024        1  eurostat  status_change   post_covid
153              Norway  2024        4  eurostat  status_change   post_covid
154              Serbia  2024        0  eurostat  status_change   post_covid

[155 rows x 6 columns]

In [10]:
sheet1_raw.to_csv(
    CLEANED_PATH / "eurostat_status_changes_cleaned.csv",
    index=False
)