## Cleaning - Eurostat long term residents Cameroon

In [2]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("..")
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

EUROPE_PATH = DATA_RAW / "europe"
CLEANED_PATH = DATA_PROCESSED / "cleaned"

CLEANED_PATH.mkdir(parents=True, exist_ok=True)

In [3]:
xls = pd.ExcelFile(EUROPE_PATH / "eurostat_citizenship_acquisition_cameroon.xlsx")
xls.sheet_names

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

['Summary',
 'Sheet 1',
 'Sheet 2',
 'Sheet 3',
 'Sheet 4',
 'Sheet 5',
 'Sheet 6',
 'Sheet 7',
 'Sheet 8',
 'Sheet 9',
 'Sheet 10',
 'Sheet 11',
 'Sheet 12',
 'Sheet 13',
 'Sheet 14',
 'Sheet 15',
 'Sheet 16',
 'Sheet 17',
 'Sheet 18',
 'Sheet 19',
 'Sheet 20',
 'Sheet 21',
 'Sheet 22',
 'Sheet 23',
 'Sheet 24',
 'Sheet 25',
 'Sheet 26',
 'Sheet 27',
 'Sheet 28',
 'Sheet 29',
 'Sheet 30',
 'Sheet 31',
 'Sheet 32',
 'Sheet 33',
 'Sheet 34',
 'Sheet 35',
 'Sheet 36',
 'Sheet 37',
 'Sheet 38',
 'Sheet 39',
 'Sheet 40',
 'Sheet 41',
 'Sheet 42',
 'Sheet 43',
 'Sheet 44',
 'Sheet 45',
 'Sheet 46',
 'Sheet 47',
 'Sheet 48',
 'Sheet 49',
 'Sheet 50',
 'Sheet 51',
 'Sheet 52',
 'Sheet 53',
 'Sheet 54',
 'Sheet 55',
 'Sheet 56',
 'Sheet 57',
 'Sheet 58',
 'Sheet 59',
 'Sheet 60',
 'Sheet 61',
 'Sheet 62',
 'Sheet 63',
 'Sheet 64',
 'Sheet 65',
 'Sheet 66',
 'Sheet 67',
 'Sheet 68',
 'Sheet 69',
 'Sheet 70',
 'Sheet 71',
 'Sheet 72',
 'Sheet 73',
 'Sheet 74',
 'Sheet 75',
 'Sheet 76',
 'Sheet 77',
 'Sheet 78',
 'Sheet 79',
 'Sheet 80',
 'Sheet 81',
 'Sheet 82',
 'Sheet 83',
 'Sheet 84',
 'Sheet 85',
 'Sheet 86',
 'Sheet 87',
 'Sheet 88',
 'Sheet 89',
 'Sheet 90',
 'Sheet 91',
 'Sheet 92',
 'Sheet 93',
 'Sheet 94',
 'Sheet 95',
 'Sheet 96',
 'Sheet 97',
 'Sheet 98',
 'Sheet 99',
 'Sheet 100',
 'Sheet 101',
 'Sheet 102',
 'Sheet 103',
 'Sheet 104',
 'Sheet 105',
 'Sheet 106',
 'Sheet 107',
 'Sheet 108',
 'Sheet 109',
 'Sheet 110',
 'Sheet 111',
 'Sheet 112',
 'Sheet 113',
 'Sheet 114',
 'Sheet 115',
 'Sheet 116',
 'Sheet 117',
 'Sheet 118',
 'Sheet 119',
 'Sheet 120',
 'Sheet 121',
 'Sheet 122',
 'Sheet 123',
 'Sheet 124',
 'Sheet 125',
 'Sheet 126',
 'Sheet 127',
 'Sheet 128',
 'Sheet 129',
 'Sheet 130',
 'Sheet 131',
 'Sheet 132',
 'Sheet 133',
 'Sheet 134',
 'Sheet 135',
 'Sheet 136',
 'Sheet 137',
 'Sheet 138',
 'Sheet 139',
 'Sheet 140',
 'Sheet 141',
 'Sheet 142',
 'Sheet 143',
 'Sheet 144',
 'Sheet 145',
 'Sheet 146',
 'Sheet 147',
 'Sheet 148',
 'Sheet 149',
 'Sheet 150',
 'Sheet 151',
 'Sheet 152',
 'Sheet 153',
 'Sheet 154',
 'Sheet 155',
 'Sheet 156',
 'Sheet 157',
 'Sheet 158',
 'Sheet 159',
 'Sheet 160',
 'Sheet 161',
 'Sheet 162']

In [5]:
sheet1_raw = pd.read_excel(
    EUROPE_PATH / "eurostat_citizenship_acquisition_cameroon.xlsx",
    sheet_name="Sheet 1",
    header=None
)

sheet1_raw

/home/linno/Documents/My project/cameroon-migration-analysis/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,Data extracted on 09/04/2026 14:08:47 from [ES...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dataset:,"Acquisition of citizenship by age group, sex a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Last updated:,27/03/2026 11:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Time frequency,NaN,Annual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Observation flags:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,b,break in time series,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,e,estimated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,ep,"estimated, provisional",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,p,provisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
sheet1_raw = sheet1_raw.drop(columns=[2, 4, 6, 8, 10, 12, 14, 16, 18], errors="ignore")
sheet1_raw = sheet1_raw.drop(index=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 57, 58, 59, 60, 61, 62, 63, 64], errors="ignore").reset_index(drop=True)

sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Belgium,738,845,872,955,1046,945,1196,1266,1311,1454
2,Bulgaria,0,0,1,0,0,1,0,0,0,1
3,Czechia,0,0,2,0,0,1,0,1,0,1
4,Denmark,14,51,14,3,2,18,26,20,15,50
5,Germany,1081,920,953,910,955,895,850,930,990,1210
6,Estonia,0,0,0,0,0,1,0,0,2,2
7,Ireland,79,43,38,33,27,24,46,57,58,75
8,Greece,0,3,3,1,0,0,5,1,1,2
9,Spain,135,196,83,123,152,258,241,357,348,351
10,France,3125,3377,3137,2502,2463,2108,3841,2859,2081,2196
11,Croatia,3,1,0,1,1,2,1,1,1,1
12,Italy,521,658,488,303,401,304,272,635,726,703
13,Cyprus,1,1,2,2,4,4,0,3,2,1
14,Latvia,0,0,0,0,0,0,0,0,0,0
15,Lithuania,0,0,0,0,0,0,0,0,0,0
16,Luxembourg,6,18,20,19,26,15,14,20,12,24
17,Hungary,2,7,1,2,1,1,3,2,5,9
18,Malta,0,0,1,1,1,0,0,1,0,1
19,Netherlands,95,88,64,74,46,70,66,67,69,79
20,Austria,32,35,24,7,30,12,12,13,13,28
21,Poland,5,6,10,5,7,7,8,9,3,7
22,Portugal,5,12,5,6,5,17,13,11,13,10
23,Romania,0,0,1,0,0,1,2,5,2,0
24,Slovenia,0,0,0,0,1,0,0,1,1,0
25,Slovakia,0,0,1,0,0,0,0,5,0,1
26,Finland,48,67,82,65,62,39,30,27,78,61
27,Sweden,93,123,145,117,47,81,81,122,100,64
28,Iceland,1,2,0,0,0,0,3,0,0,0
29,Liechtenstein,0,0,1,0,0,0,0,0,0,0
30,Norway,27,38,39,15,25,15,15,16,27,13
31,Switzerland,156,227,211,166,151,122,111,146,167,157
32,United Kingdom,471,508,414,461,489,:,:,:,:,:
33,North Macedonia,:,:,:,:,:,:,:,:,:,:
34,Georgia,:,:,:,:,:,:,:,:,:,0
35,Albania,:,:,:,:,:,:,:,0,:,2
36,Türkiye,:,:,:,:,:,:,:,:,:,:
37,Ukraine,:,:,:,:,:,:,:,:,:,:
38,Belarus,:,:,:,:,:,:,:,:,:,:
39,Russia,:,:,:,:,:,:,:,:,:,:
40,Armenia,:,:,:,:,:,:,:,:,:,:
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
sheet1_raw = sheet1_raw.drop(index=[41], errors="ignore").reset_index(drop=True)

sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Belgium,738,845,872,955,1046,945,1196,1266,1311,1454
2,Bulgaria,0,0,1,0,0,1,0,0,0,1
3,Czechia,0,0,2,0,0,1,0,1,0,1
4,Denmark,14,51,14,3,2,18,26,20,15,50
5,Germany,1081,920,953,910,955,895,850,930,990,1210
6,Estonia,0,0,0,0,0,1,0,0,2,2
7,Ireland,79,43,38,33,27,24,46,57,58,75
8,Greece,0,3,3,1,0,0,5,1,1,2
9,Spain,135,196,83,123,152,258,241,357,348,351
10,France,3125,3377,3137,2502,2463,2108,3841,2859,2081,2196
11,Croatia,3,1,0,1,1,2,1,1,1,1
12,Italy,521,658,488,303,401,304,272,635,726,703
13,Cyprus,1,1,2,2,4,4,0,3,2,1
14,Latvia,0,0,0,0,0,0,0,0,0,0
15,Lithuania,0,0,0,0,0,0,0,0,0,0
16,Luxembourg,6,18,20,19,26,15,14,20,12,24
17,Hungary,2,7,1,2,1,1,3,2,5,9
18,Malta,0,0,1,1,1,0,0,1,0,1
19,Netherlands,95,88,64,74,46,70,66,67,69,79
20,Austria,32,35,24,7,30,12,12,13,13,28
21,Poland,5,6,10,5,7,7,8,9,3,7
22,Portugal,5,12,5,6,5,17,13,11,13,10
23,Romania,0,0,1,0,0,1,2,5,2,0
24,Slovenia,0,0,0,0,1,0,0,1,1,0
25,Slovakia,0,0,1,0,0,0,0,5,0,1
26,Finland,48,67,82,65,62,39,30,27,78,61
27,Sweden,93,123,145,117,47,81,81,122,100,64
28,Iceland,1,2,0,0,0,0,3,0,0,0
29,Liechtenstein,0,0,1,0,0,0,0,0,0,0
30,Norway,27,38,39,15,25,15,15,16,27,13
31,Switzerland,156,227,211,166,151,122,111,146,167,157
32,United Kingdom,471,508,414,461,489,:,:,:,:,:
33,North Macedonia,:,:,:,:,:,:,:,:,:,:
34,Georgia,:,:,:,:,:,:,:,:,:,0
35,Albania,:,:,:,:,:,:,:,0,:,2
36,Türkiye,:,:,:,:,:,:,:,:,:,:
37,Ukraine,:,:,:,:,:,:,:,:,:,:
38,Belarus,:,:,:,:,:,:,:,:,:,:
39,Russia,:,:,:,:,:,:,:,:,:,:
40,Armenia,:,:,:,:,:,:,:,:,:,:

In [8]:
sheet1_raw = sheet1_raw.replace(":", 0)
sheet1_raw = sheet1_raw.rename(
    columns={"TIME": "destination_country"}
)

sheet1_raw

,0,1,3,5,7,9,11,13,15,17,19
0,TIME,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Belgium,738,845,872,955,1046,945,1196,1266,1311,1454
2,Bulgaria,0,0,1,0,0,1,0,0,0,1
3,Czechia,0,0,2,0,0,1,0,1,0,1
4,Denmark,14,51,14,3,2,18,26,20,15,50
5,Germany,1081,920,953,910,955,895,850,930,990,1210
6,Estonia,0,0,0,0,0,1,0,0,2,2
7,Ireland,79,43,38,33,27,24,46,57,58,75
8,Greece,0,3,3,1,0,0,5,1,1,2
9,Spain,135,196,83,123,152,258,241,357,348,351
10,France,3125,3377,3137,2502,2463,2108,3841,2859,2081,2196
11,Croatia,3,1,0,1,1,2,1,1,1,1
12,Italy,521,658,488,303,401,304,272,635,726,703
13,Cyprus,1,1,2,2,4,4,0,3,2,1
14,Latvia,0,0,0,0,0,0,0,0,0,0
15,Lithuania,0,0,0,0,0,0,0,0,0,0
16,Luxembourg,6,18,20,19,26,15,14,20,12,24
17,Hungary,2,7,1,2,1,1,3,2,5,9
18,Malta,0,0,1,1,1,0,0,1,0,1
19,Netherlands,95,88,64,74,46,70,66,67,69,79
20,Austria,32,35,24,7,30,12,12,13,13,28
21,Poland,5,6,10,5,7,7,8,9,3,7
22,Portugal,5,12,5,6,5,17,13,11,13,10
23,Romania,0,0,1,0,0,1,2,5,2,0
24,Slovenia,0,0,0,0,1,0,0,1,1,0
25,Slovakia,0,0,1,0,0,0,0,5,0,1
26,Finland,48,67,82,65,62,39,30,27,78,61
27,Sweden,93,123,145,117,47,81,81,122,100,64
28,Iceland,1,2,0,0,0,0,3,0,0,0
29,Liechtenstein,0,0,1,0,0,0,0,0,0,0
30,Norway,27,38,39,15,25,15,15,16,27,13
31,Switzerland,156,227,211,166,151,122,111,146,167,157
32,United Kingdom,471,508,414,461,489,0,0,0,0,0
33,North Macedonia,0,0,0,0,0,0,0,0,0,0
34,Georgia,0,0,0,0,0,0,0,0,0,0
35,Albania,0,0,0,0,0,0,0,0,0,2
36,Türkiye,0,0,0,0,0,0,0,0,0,0
37,Ukraine,0,0,0,0,0,0,0,0,0,0
38,Belarus,0,0,0,0,0,0,0,0,0,0
39,Russia,0,0,0,0,0,0,0,0,0,0
40,Armenia,0,0,0,0,0,0,0,0,0,0

In [9]:
# Mettre la première ligne comme entête
sheet1_raw.columns = sheet1_raw.iloc[0]
sheet1_raw = sheet1_raw.iloc[1:].reset_index(drop=True)

# Renommer TIME en destination_country
sheet1_raw = sheet1_raw.rename(
    columns={"TIME": "destination_country"}
)

# Supprimer la ligne GEO (Labels) si elle existe encore
sheet1_raw = sheet1_raw[
    sheet1_raw["destination_country"] != "GEO (Labels)"
]

# Passer du format large au format long
sheet1_raw = sheet1_raw.melt(
    id_vars=["destination_country"],
    var_name="year",
    value_name="permit"
)

# Nettoyer les types
sheet1_raw["year"] = sheet1_raw["year"].astype(int)

sheet1_raw["permit"] = (
    pd.to_numeric(sheet1_raw["permit"], errors="coerce")
    .fillna(0)
    .astype(int)
)

# Réordonner les colonnes
sheet1_raw = sheet1_raw[
    ["destination_country", "year", "permit"]
]

sheet1_raw

    destination_country  year  permit
0               Belgium  2015     738
1              Bulgaria  2015       0
2               Czechia  2015       0
3               Denmark  2015      14
4               Germany  2015    1081
..                  ...   ...     ...
395             Türkiye  2024       0
396             Ukraine  2024       0
397             Belarus  2024       0
398              Russia  2024       0
399             Armenia  2024       0

[400 rows x 3 columns]

In [10]:
# Renommer permit en permits
sheet1_raw = sheet1_raw.rename(
    columns={"permit": "permits"}
)

# Ajouter les colonnes source et nature
sheet1_raw["source"] = "eurostat"
sheet1_raw["nature"] = "citizenship_acquisition"

# Ajouter la période Covid
def classify_covid_period(year):
    if year < 2020:
        return "pre_covid"
    elif year in [2020, 2021]:
        return "covid"
    else:
        return "post_covid"

sheet1_raw["covid_period"] = sheet1_raw["year"].apply(classify_covid_period)

# Réordonner les colonnes
sheet1_raw = sheet1_raw[
    [
        "destination_country",
        "year",
        "permits",
        "source",
        "nature",
        "covid_period"
    ]
]

sheet1_raw

    destination_country  year  permits    source         nature covid_period
0               Belgium  2015      738  eurostat  citizenship_acquisition    pre_covid
1              Bulgaria  2015        0  eurostat  citizenship_acquisition    pre_covid
2               Czechia  2015        0  eurostat  citizenship_acquisition    pre_covid
3               Denmark  2015       14  eurostat  citizenship_acquisition    pre_covid
4               Germany  2015     1081  eurostat  citizenship_acquisition    pre_covid
..                  ...   ...      ...       ...            ...          ...
395             Türkiye  2024        0  eurostat  citizenship_acquisition   post_covid
396             Ukraine  2024        0  eurostat  citizenship_acquisition   post_covid
397             Belarus  2024        0  eurostat  citizenship_acquisition   post_covid
398              Russia  2024        0  eurostat  citizenship_acquisition   post_covid
399             Armenia  2024        0  eurostat  citizenship_acquisition   post_covid

[400 rows x 6 columns]

In [12]:
sheet1_raw.to_csv(
    CLEANED_PATH / "eurostat_citizenship_acquisition_cleaned.csv",
    index=False
)