## Nettoyage - base de données migration OCDE

In [15]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("..")
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

GLOBAL_PATH = DATA_RAW / "global"
CLEANED_PATH = DATA_PROCESSED / "cleaned"

CLEANED_PATH.mkdir(parents=True, exist_ok=True)

In [16]:
xls = pd.read_csv(GLOBAL_PATH / "oecd_migration_database_raw.csv")
xls.head()

/tmp/ipykernel_8905/4289521397.py:1: DtypeWarning: Columns (0: Flag Codes, 1: Flags) have mixed types. Specify dtype option on import or set low_memory=False.
  xls = pd.read_csv(GLOBAL_PATH / "oecd_migration_database_raw.csv")

,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
0,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,1999,1999,434.0,NaN,NaN
1,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2000,2000,398.0,NaN,NaN
2,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2001,2001,225.0,NaN,NaN
3,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2002,2002,345.0,NaN,NaN
4,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2003,2003,544.0,NaN,NaN

In [17]:
sheet1_raw = pd.read_csv(
    GLOBAL_PATH / "oecd_migration_database_raw.csv",
    header=None
)

sheet1_raw

/tmp/ipykernel_8905/3517392079.py:1: DtypeWarning: Columns (0: 8, 1: 9, 2: 10, 3: 11, 4: 12) have mixed types. Specify dtype option on import or set low_memory=False.
  sheet1_raw = pd.read_csv(

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
1,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,1999,1999,434,NaN,NaN
2,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2000,2000,398,NaN,NaN
3,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2001,2001,225,NaN,NaN
4,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2002,2002,345,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999996,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2014,2014,0,NaN,NaN
999997,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2016,2016,3,NaN,NaN
999998,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2017,2017,3,NaN,NaN
999999,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2018,2018,3,NaN,NaN
1000000,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2019,2019,3,NaN,NaN

In [18]:
sheet1_raw = sheet1_raw[
    (sheet1_raw.index == 0) | (sheet1_raw[0] == "CMR")
].copy()

sheet1_raw

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
76839,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,1999,1999,0,NaN,NaN
76840,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2000,2000,1,NaN,NaN
76841,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2001,2001,1,NaN,NaN
76842,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2002,2002,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999561,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2016,2016,3,NaN,NaN
999562,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2017,2017,3,NaN,NaN
999563,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2018,2018,3,NaN,NaN
999564,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2019,2019,3,NaN,NaN
999565,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2020,2020,0,NaN,NaN

In [19]:
years = pd.to_numeric(sheet1_raw[9], errors="coerce")

sheet1_raw = sheet1_raw[
    (sheet1_raw.index == 0) |
    ((years >= 2015) & (years <= 2024))
].copy()

In [20]:
sheet1_raw

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
76855,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2015,2015,11,NaN,NaN
76856,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2016,2016,10,NaN,NaN
76857,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2017,2017,7,NaN,NaN
76858,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2018,2018,7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999561,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2016,2016,3,NaN,NaN
999562,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2017,2017,3,NaN,NaN
999563,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2018,2018,3,NaN,NaN
999564,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2019,2019,3,NaN,NaN
999565,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2020,2020,0,NaN,NaN

In [21]:
sheet1_raw = sheet1_raw[
    (sheet1_raw.index == 0) | (sheet1_raw[5] == "Total")
].copy()

sheet1_raw = sheet1_raw.drop(columns=[11, 12])

sheet1_raw

,0,1,2,3,4,5,6,7,8,9,10
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value
76916,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2015,2015,26
76917,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2016,2016,18
76918,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2017,2017,11
76919,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2018,2018,15
...,...,...,...,...,...,...,...,...,...,...,...
990575,CMR,Cameroon,B16,Acquisition of nationality by country of forme...,TOT,Total,LUX,Luxembourg,2021,2021,14
995852,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2016,2016,3
995853,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2017,2017,3
995854,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2018,2018,3
995855,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2019,2019,3

In [22]:
sheet1_raw.head(50)

,0,1,2,3,4,5,6,7,8,9,10
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value
76916,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2015,2015,26
76917,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2016,2016,18
76918,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2017,2017,11
76919,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2018,2018,15
76920,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2019,2019,15
76921,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2020,2020,19
76922,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2021,2021,25
76940,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUS,Australia,2015,2015,0
76941,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUS,Australia,2016,2016,0
76961,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2015,2015,0
76962,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2016,2016,18
76963,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2019,2019,5
76964,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2020,2020,5
76965,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2021,2021,0
77052,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2015,2015,93
77053,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2016,2016,72
77054,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2017,2017,85
77055,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2018,2018,58
77056,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2019,2019,41
77057,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2020,2020,42
77058,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2021,2021,55
77076,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2015,2015,26
77077,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2016,2016,40
77078,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2017,2017,49
77079,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2018,2018,55
77080,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2019,2019,41
77081,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2020,2020,23
77082,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2021,2021,36
77102,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2015,2015,0
77103,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2016,2016,0
77104,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2017,2017,60
77105,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2018,2018,30
77106,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2019,2019,30
77107,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2020,2020,20
77108,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2021,2021,30
77163,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2015,2015,1504
77164,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2016,2016,1611
77165,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2017,2017,1698
77166,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2018,2018,1754
77167,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2019,2019,1775
77168,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2020,2020,1735
77169,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2021,2021,2765
77177,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2015,2015,527
77178,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2016,2016,519
77179,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2017,2017,409
77180,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2018,2018,424
77181,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2019,2019,329
77182,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2020,2020,418
77183,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2021,2021,470

In [23]:
sheet1_raw = sheet1_raw.drop(columns=[0, 1, 2, 4, 5, 6, 8])

sheet1_raw = sheet1_raw.reset_index(drop=True)

sheet1_raw

,3,7,9,10
0,Variable,Country,Year,Value
1,Inflows of foreign population by nationality,Australia,2015,26
2,Inflows of foreign population by nationality,Australia,2016,18
3,Inflows of foreign population by nationality,Australia,2017,11
4,Inflows of foreign population by nationality,Australia,2018,15
...,...,...,...,...
1026,Acquisition of nationality by country of forme...,Luxembourg,2021,14
1027,Inflows of foreign workers by nationality,Australia,2016,3
1028,Inflows of foreign workers by nationality,Australia,2017,3
1029,Inflows of foreign workers by nationality,Australia,2018,3
1030,Inflows of foreign workers by nationality,Australia,2019,3

In [24]:
sheet1_raw.columns = sheet1_raw.iloc[0]

sheet1_raw = sheet1_raw.drop(index=0).reset_index(drop=True)

sheet1_raw.columns.name = None

sheet1_raw

,Variable,Country,Year,Value
0,Inflows of foreign population by nationality,Australia,2015,26
1,Inflows of foreign population by nationality,Australia,2016,18
2,Inflows of foreign population by nationality,Australia,2017,11
3,Inflows of foreign population by nationality,Australia,2018,15
4,Inflows of foreign population by nationality,Australia,2019,15
...,...,...,...,...
1025,Acquisition of nationality by country of forme...,Luxembourg,2021,14
1026,Inflows of foreign workers by nationality,Australia,2016,3
1027,Inflows of foreign workers by nationality,Australia,2017,3
1028,Inflows of foreign workers by nationality,Australia,2018,3
1029,Inflows of foreign workers by nationality,Australia,2019,3

In [25]:
# Renommer permit en permits
sheet1_raw = sheet1_raw.rename(
    columns={"Variable": "nature", "Value": "permits", "Country": "destination_country", "Year": "year"}
)

# Ajouter les colonnes source et nature
sheet1_raw["source"] = "oecd"

# Ajouter la période Covid
def classify_covid_period(year):
    if year < 2020:
        return "pre_covid"
    elif year in [2020, 2021]:
        return "covid"
    else:
        return "post_covid"

sheet1_raw["covid_period"] = sheet1_raw["year"].apply(classify_covid_period)

# Ajouter une variable courte sans modifier les libellés de nature
nature_mapping = {
    "Inflows of foreign population by nationality": "inflow",
    "Outflows of foreign population by nationality": "outflow",
    "Inflows of asylum seekers by nationality": "asylum_inflow",
    "Stock of foreign-born population by country of birth": "stock_birth",
    "Stock of foreign population by nationality": "stock_nationality",
    "Acquisition of nationality by country of former nationality": "citizenship_acquisition",
    "Inflows of foreign workers by nationality": "worker_inflow",
    "Inflows of seasonal foreign workers by nationality": "seasonal_worker_inflow",
}

sheet1_raw["variable"] = sheet1_raw["nature"].map(nature_mapping)

missing_nature = sheet1_raw.loc[sheet1_raw["variable"].isna(), "nature"].drop_duplicates()
if not missing_nature.empty:
    raise ValueError(f"Natures non mappees: {missing_nature.tolist()}")

# Réordonner les colonnes
sheet1_raw = sheet1_raw[
    [
        "destination_country",
        "year",
        "permits",
        "source",
        "nature",
        "variable",
        "covid_period"
    ]
]

sheet1_raw

,destination_country,year,permits,source,nature,covid_period
0,Australia,2015,26,oecd,Inflows of foreign population by nationality,pre_covid
1,Australia,2016,18,oecd,Inflows of foreign population by nationality,pre_covid
2,Australia,2017,11,oecd,Inflows of foreign population by nationality,pre_covid
3,Australia,2018,15,oecd,Inflows of foreign population by nationality,pre_covid
4,Australia,2019,15,oecd,Inflows of foreign population by nationality,pre_covid
...,...,...,...,...,...,...
1025,Luxembourg,2021,14,oecd,Acquisition of nationality by country of forme...,covid
1026,Australia,2016,3,oecd,Inflows of foreign workers by nationality,pre_covid
1027,Australia,2017,3,oecd,Inflows of foreign workers by nationality,pre_covid
1028,Australia,2018,3,oecd,Inflows of foreign workers by nationality,pre_covid
1029,Australia,2019,3,oecd,Inflows of foreign workers by nationality,pre_covid

In [ ]:
sheet1_raw.to_csv(
    CLEANED_PATH / "oecd_migration_cleaned.csv",
    index=False
)

In [27]:
nature_mapping = {
    "Inflows of foreign population by nationality": "inflow",
    "Outflows of foreign population by nationality": "outflow",
    "Inflows of asylum seekers by nationality": "asylum_inflow",
    "Stock of foreign-born population by country of birth": "stock_birth",
    "Stock of foreign population by nationality": "stock_nationality",
    "Acquisition of nationality by country of former nationality": "citizenship_acquisition",
    "Inflows of foreign workers by nationality": "worker_inflow",
    "Inflows of seasonal foreign workers by nationality": "seasonal_worker_inflow",
}

sheet1_raw["variable"] = sheet1_raw["nature"].map(nature_mapping)

sheet1_raw

,destination_country,year,permits,source,nature,covid_period,variable
0,Australia,2015,26,oecd,Inflows of foreign population by nationality,pre_covid,inflow
1,Australia,2016,18,oecd,Inflows of foreign population by nationality,pre_covid,inflow
2,Australia,2017,11,oecd,Inflows of foreign population by nationality,pre_covid,inflow
3,Australia,2018,15,oecd,Inflows of foreign population by nationality,pre_covid,inflow
4,Australia,2019,15,oecd,Inflows of foreign population by nationality,pre_covid,inflow
...,...,...,...,...,...,...,...
1025,Luxembourg,2021,14,oecd,Acquisition of nationality by country of forme...,covid,citizenship_acquisition
1026,Australia,2016,3,oecd,Inflows of foreign workers by nationality,pre_covid,worker_inflow
1027,Australia,2017,3,oecd,Inflows of foreign workers by nationality,pre_covid,worker_inflow
1028,Australia,2018,3,oecd,Inflows of foreign workers by nationality,pre_covid,worker_inflow
1029,Australia,2019,3,oecd,Inflows of foreign workers by nationality,pre_covid,worker_inflow

In [28]:
sheet1_raw = sheet1_raw.drop(columns=["nature"])

sheet1_raw = sheet1_raw.rename(
    columns={
        "variable": "nature",
        "permits": "value",
    }
)
sheet1_raw = sheet1_raw[
    [
        "destination_country",
        "year",
        "value",
        "source",
        "nature",
        "covid_period",
    ]
]

sheet1_raw

,destination_country,year,value,source,nature,covid_period
0,Australia,2015,26,oecd,inflow,pre_covid
1,Australia,2016,18,oecd,inflow,pre_covid
2,Australia,2017,11,oecd,inflow,pre_covid
3,Australia,2018,15,oecd,inflow,pre_covid
4,Australia,2019,15,oecd,inflow,pre_covid
...,...,...,...,...,...,...
1025,Luxembourg,2021,14,oecd,citizenship_acquisition,covid
1026,Australia,2016,3,oecd,worker_inflow,pre_covid
1027,Australia,2017,3,oecd,worker_inflow,pre_covid
1028,Australia,2018,3,oecd,worker_inflow,pre_covid
1029,Australia,2019,3,oecd,worker_inflow,pre_covid