# 08 - Cleaning OECD Migration Database Indicators

This notebook filters and prepares OECD migration indicators related to Cameroon.

Analytical role:

- provides complementary evidence for Q1, Q2 and Q3
- keeps OECD indicators separate from UN DESA and Eurostat indicators
- standardizes selected measures for later integration into the analytical master tables

OECD indicators are used as supporting evidence because their definitions and coverage differ from the main sources used in each research question.

## 1. Objective of the Notebook

The objective of this notebook is to filter, clean and structure OECD migration indicators related to Cameroon.

The raw OECD file contains several migration indicators and many countries. This notebook keeps only the records relevant to Cameroon and prepares a clean output that can be used later in the analytical pipeline.

The cleaned output produced in this notebook is:

```text
data/processed/cleaned/oecd_migration_cleaned.csv
```

## 2. Analytical Role in the Project

This dataset provides complementary evidence for the project.

It can support the analysis of:

- migrant inflows
- migrant outflows
- asylum-related inflows
- migrant stock by country of birth
- migrant stock by nationality
- acquisition of nationality

However, OECD data is not used as the main source for every research question. It is used only when the indicator definition and country coverage are compatible with the analysis.

## 3. Methodological Warning

OECD data should not be merged blindly with UN DESA or Eurostat data.

The reason is simple: each source measures a different phenomenon.

For example:

- UN DESA mainly supports migrant stock analysis at global level.
- Eurostat first permits measure administrative entries in European countries.
- Eurostat long-term residence and citizenship acquisition measure post-arrival administrative outcomes.
- OECD indicators provide additional migration measures for OECD countries.

For this reason, OECD indicators are kept clearly identified with the `source` column and the `nature` variable.

## 4. Libraries, Paths and Output Folder

This section imports the required Python libraries and defines the main project paths.

The notebook uses:

- `pandas` for data manipulation
- `Path` from `pathlib` for reliable file path management

The cleaned output folder is also created if it does not already exist.

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("..")
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

GLOBAL_PATH = DATA_RAW / "global"
CLEANED_PATH = DATA_PROCESSED / "cleaned"

CLEANED_PATH.mkdir(parents=True, exist_ok=True)

## 5. Raw Data Loading

The raw OECD migration database is loaded from the `data/raw/global/` folder.

The first loading step is used to inspect the file and understand its raw structure before applying filters.

In [ ]:
xls = pd.read_csv(GLOBAL_PATH / "oecd_migration_database_raw.csv")
xls.head()

C:\Users\Linno\AppData\Local\Temp\ipykernel_17896\4289521397.py:1: DtypeWarning: Columns (0: Flag Codes, 1: Flags) have mixed types. Specify dtype option on import or set low_memory=False.
  xls = pd.read_csv(GLOBAL_PATH / "oecd_migration_database_raw.csv")

,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
0,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,1999,1999,434.0,NaN,NaN
1,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2000,2000,398.0,NaN,NaN
2,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2001,2001,225.0,NaN,NaN
3,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2002,2002,345.0,NaN,NaN
4,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2003,2003,544.0,NaN,NaN

In [ ]:
sheet1_raw = pd.read_csv(
    GLOBAL_PATH / "oecd_migration_database_raw.csv",
    header=None
)

sheet1_raw

C:\Users\Linno\AppData\Local\Temp\ipykernel_17896\3517392079.py:1: DtypeWarning: Columns (0: 8, 1: 9, 2: 10, 3: 11, 4: 12) have mixed types. Specify dtype option on import or set low_memory=False.
  sheet1_raw = pd.read_csv(

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
1,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,1999,1999,434,NaN,NaN
2,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2000,2000,398,NaN,NaN
3,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2001,2001,225,NaN,NaN
4,AFG,Afghanistan,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2002,2002,345,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999996,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2014,2014,0,NaN,NaN
999997,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2016,2016,3,NaN,NaN
999998,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2017,2017,3,NaN,NaN
999999,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2018,2018,3,NaN,NaN
1000000,CRI,Costa Rica,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2019,2019,3,NaN,NaN

## 6. Filtering Cameroon-Related Records

The OECD raw file contains multiple countries and indicators.

This step keeps:

- the header row
- rows where the country code corresponds to Cameroon (`CMR`)

This ensures that the cleaned dataset focuses only on Cameroonian migration-related records.

In [ ]:
sheet1_raw = sheet1_raw[
    (sheet1_raw.index == 0) | (sheet1_raw[0] == "CMR")
].copy()

sheet1_raw

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
76839,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,1999,1999,0,NaN,NaN
76840,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2000,2000,1,NaN,NaN
76841,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2001,2001,1,NaN,NaN
76842,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2002,2002,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999561,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2016,2016,3,NaN,NaN
999562,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2017,2017,3,NaN,NaN
999563,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2018,2018,3,NaN,NaN
999564,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2019,2019,3,NaN,NaN
999565,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2020,2020,0,NaN,NaN

## 7. Filtering the Study Period

The project focuses on the 2015–2024 period.

This step converts the year column into a numeric field and keeps only records within the project period.

The header row is preserved so that the dataset can be properly renamed later.

In [ ]:
years = pd.to_numeric(sheet1_raw[9], errors="coerce")

sheet1_raw = sheet1_raw[
    (sheet1_raw.index == 0) |
    ((years >= 2015) & (years <= 2024))
].copy()

In [ ]:
sheet1_raw

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
76855,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2015,2015,11,NaN,NaN
76856,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2016,2016,10,NaN,NaN
76857,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2017,2017,7,NaN,NaN
76858,CMR,Cameroon,B11,Inflows of foreign population by nationality,WMN,Women,AUS,Australia,2018,2018,7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999561,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2016,2016,3,NaN,NaN
999562,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2017,2017,3,NaN,NaN
999563,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2018,2018,3,NaN,NaN
999564,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2019,2019,3,NaN,NaN
999565,CMR,Cameroon,B21,Inflows of foreign workers by nationality,WMN,Women,AUS,Australia,2020,2020,0,NaN,NaN

## 8. Keeping Total-Level Records and Removing Unused Columns

This step keeps records where the selected population category is `Total`.

The goal is to avoid unnecessary subgroup breakdowns and keep the dataset aligned with the project’s macro-level analysis.

Unused columns are removed to simplify the structure before standardization.

In [ ]:
sheet1_raw = sheet1_raw[
    (sheet1_raw.index == 0) | (sheet1_raw[5] == "Total")
].copy()

sheet1_raw = sheet1_raw.drop(columns=[11, 12])

sheet1_raw

,0,1,2,3,4,5,6,7,8,9,10
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value
76916,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2015,2015,26
76917,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2016,2016,18
76918,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2017,2017,11
76919,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2018,2018,15
...,...,...,...,...,...,...,...,...,...,...,...
990575,CMR,Cameroon,B16,Acquisition of nationality by country of forme...,TOT,Total,LUX,Luxembourg,2021,2021,14
995852,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2016,2016,3
995853,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2017,2017,3
995854,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2018,2018,3
995855,CMR,Cameroon,B21,Inflows of foreign workers by nationality,TOT,Total,AUS,Australia,2019,2019,3

In [ ]:
sheet1_raw.head(50)

,0,1,2,3,4,5,6,7,8,9,10
0,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value
76916,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2015,2015,26
76917,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2016,2016,18
76918,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2017,2017,11
76919,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2018,2018,15
76920,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2019,2019,15
76921,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2020,2020,19
76922,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2021,2021,25
76940,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUS,Australia,2015,2015,0
76941,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUS,Australia,2016,2016,0
76961,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2015,2015,0
76962,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2016,2016,18
76963,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2019,2019,5
76964,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2020,2020,5
76965,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUS,Australia,2021,2021,0
77052,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2015,2015,93
77053,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2016,2016,72
77054,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2017,2017,85
77055,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2018,2018,58
77056,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2019,2019,41
77057,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2020,2020,42
77058,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2021,2021,55
77076,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2015,2015,26
77077,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2016,2016,40
77078,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2017,2017,49
77079,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2018,2018,55
77080,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2019,2019,41
77081,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2020,2020,23
77082,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,AUT,Austria,2021,2021,36
77102,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2015,2015,0
77103,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2016,2016,0
77104,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2017,2017,60
77105,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2018,2018,30
77106,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2019,2019,30
77107,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2020,2020,20
77108,CMR,Cameroon,B13,Inflows of asylum seekers by nationality,TOT,Total,AUT,Austria,2021,2021,30
77163,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2015,2015,1504
77164,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2016,2016,1611
77165,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2017,2017,1698
77166,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2018,2018,1754
77167,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2019,2019,1775
77168,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2020,2020,1735
77169,CMR,Cameroon,B11,Inflows of foreign population by nationality,TOT,Total,BEL,Belgium,2021,2021,2765
77177,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2015,2015,527
77178,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2016,2016,519
77179,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2017,2017,409
77180,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2018,2018,424
77181,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2019,2019,329
77182,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2020,2020,418
77183,CMR,Cameroon,B12,Outflows of foreign population by nationality,TOT,Total,BEL,Belgium,2021,2021,470

## 9. Column Selection and Header Reconstruction

The raw OECD file contains technical and metadata columns that are not needed for the analysis.

This step removes unnecessary columns, resets the index and uses the first remaining row as the official column header.

The objective is to obtain a readable table with clear analytical variables.

In [ ]:
sheet1_raw = sheet1_raw.drop(columns=[0, 1, 2, 4, 5, 6, 8])

sheet1_raw = sheet1_raw.reset_index(drop=True)

sheet1_raw

,3,7,9,10
0,Variable,Country,Year,Value
1,Inflows of foreign population by nationality,Australia,2015,26
2,Inflows of foreign population by nationality,Australia,2016,18
3,Inflows of foreign population by nationality,Australia,2017,11
4,Inflows of foreign population by nationality,Australia,2018,15
...,...,...,...,...
1026,Acquisition of nationality by country of forme...,Luxembourg,2021,14
1027,Inflows of foreign workers by nationality,Australia,2016,3
1028,Inflows of foreign workers by nationality,Australia,2017,3
1029,Inflows of foreign workers by nationality,Australia,2018,3
1030,Inflows of foreign workers by nationality,Australia,2019,3

In [ ]:
sheet1_raw.columns = sheet1_raw.iloc[0]

sheet1_raw = sheet1_raw.drop(index=0).reset_index(drop=True)

sheet1_raw.columns.name = None

sheet1_raw

,Variable,Country,Year,Value
0,Inflows of foreign population by nationality,Australia,2015,26
1,Inflows of foreign population by nationality,Australia,2016,18
2,Inflows of foreign population by nationality,Australia,2017,11
3,Inflows of foreign population by nationality,Australia,2018,15
4,Inflows of foreign population by nationality,Australia,2019,15
...,...,...,...,...
1025,Acquisition of nationality by country of forme...,Luxembourg,2021,14
1026,Inflows of foreign workers by nationality,Australia,2016,3
1027,Inflows of foreign workers by nationality,Australia,2017,3
1028,Inflows of foreign workers by nationality,Australia,2018,3
1029,Inflows of foreign workers by nationality,Australia,2019,3

## 10. Standardizing Variable Names and Indicator Categories

This section renames the main columns into consistent project-level names.

The notebook also creates a simplified indicator variable.

The original OECD indicator labels are mapped into shorter categories such as:

- `inflow`
- `outflow`
- `asylum_inflow`
- `stock_birth`
- `stock_nationality`
- `citizenship_acquisition`

This makes the dataset easier to analyze while preserving the meaning of each indicator.

In [ ]:
# Rename permit to permits
sheet1_raw = sheet1_raw.rename(
    columns={"Variable": "nature", "Value": "permits", "Country": "destination_country", "Year": "year"}
)

# Add source and nature columns
sheet1_raw["source"] = "oecd"

# Add a short variable without changing the original nature labels
nature_mapping = {
    "Inflows of foreign population by nationality": "inflow",
    "Outflows of foreign population by nationality": "outflow",
    "Inflows of asylum seekers by nationality": "asylum_inflow",
    "Stock of foreign-born population by country of birth": "stock_birth",
    "Stock of foreign population by nationality": "stock_nationality",
    "Acquisition of nationality by country of former nationality": "citizenship_acquisition",
    "Inflows of foreign workers by nationality": "worker_inflow",
    "Inflows of seasonal foreign workers by nationality": "seasonal_worker_inflow",
}

sheet1_raw["variable"] = sheet1_raw["nature"].map(nature_mapping)

missing_nature = sheet1_raw.loc[sheet1_raw["variable"].isna(), "nature"].drop_duplicates()
if not missing_nature.empty:
    raise ValueError(f"Natures non mappees: {missing_nature.tolist()}")

# Reorder columns
sheet1_raw = sheet1_raw[
    [
        "destination_country",
        "year",
        "permits",
        "source",
        "nature",
        "variable",
    ]
]

sheet1_raw

,destination_country,year,permits,source,nature,variable
0,Australia,2015,26,oecd,Inflows of foreign population by nationality,inflow
1,Australia,2016,18,oecd,Inflows of foreign population by nationality,inflow
2,Australia,2017,11,oecd,Inflows of foreign population by nationality,inflow
3,Australia,2018,15,oecd,Inflows of foreign population by nationality,inflow
4,Australia,2019,15,oecd,Inflows of foreign population by nationality,inflow
...,...,...,...,...,...,...
1025,Luxembourg,2021,14,oecd,Acquisition of nationality by country of forme...,citizenship_acquisition
1026,Australia,2016,3,oecd,Inflows of foreign workers by nationality,worker_inflow
1027,Australia,2017,3,oecd,Inflows of foreign workers by nationality,worker_inflow
1028,Australia,2018,3,oecd,Inflows of foreign workers by nationality,worker_inflow
1029,Australia,2019,3,oecd,Inflows of foreign workers by nationality,worker_inflow

In [ ]:
nature_mapping = {
    "Inflows of foreign population by nationality": "inflow",
    "Outflows of foreign population by nationality": "outflow",
    "Inflows of asylum seekers by nationality": "asylum_inflow",
    "Stock of foreign-born population by country of birth": "stock_birth",
    "Stock of foreign population by nationality": "stock_nationality",
    "Acquisition of nationality by country of former nationality": "citizenship_acquisition",
    "Inflows of foreign workers by nationality": "worker_inflow",
    "Inflows of seasonal foreign workers by nationality": "seasonal_worker_inflow",
}

sheet1_raw["variable"] = sheet1_raw["nature"].map(nature_mapping)

sheet1_raw

,destination_country,year,permits,source,nature,variable
0,Australia,2015,26,oecd,Inflows of foreign population by nationality,inflow
1,Australia,2016,18,oecd,Inflows of foreign population by nationality,inflow
2,Australia,2017,11,oecd,Inflows of foreign population by nationality,inflow
3,Australia,2018,15,oecd,Inflows of foreign population by nationality,inflow
4,Australia,2019,15,oecd,Inflows of foreign population by nationality,inflow
...,...,...,...,...,...,...
1025,Luxembourg,2021,14,oecd,Acquisition of nationality by country of forme...,citizenship_acquisition
1026,Australia,2016,3,oecd,Inflows of foreign workers by nationality,worker_inflow
1027,Australia,2017,3,oecd,Inflows of foreign workers by nationality,worker_inflow
1028,Australia,2018,3,oecd,Inflows of foreign workers by nationality,worker_inflow
1029,Australia,2019,3,oecd,Inflows of foreign workers by nationality,worker_inflow

## 11. Final Dataset Structure

The cleaned OECD dataset is reorganized into a consistent structure.

The final columns are:

- `destination_country`: OECD destination country
- `year`: reference year
- `value`: observed indicator value
- `source`: data source
- `nature`: simplified OECD indicator type

This structure allows the dataset to be used later in the project while keeping it separate from indicators coming from other sources.

In [ ]:
sheet1_raw = sheet1_raw.drop(columns=["nature"])

sheet1_raw = sheet1_raw.rename(
    columns={
        "variable": "nature",
        "permits": "value",
    }
)
sheet1_raw = sheet1_raw[
    [
        "destination_country",
        "year",
        "value",
        "source",
        "nature",
    ]
]

sheet1_raw

     destination_country  year value source                   nature
0              Australia  2015    26   oecd                   inflow
1              Australia  2016    18   oecd                   inflow
2              Australia  2017    11   oecd                   inflow
3              Australia  2018    15   oecd                   inflow
4              Australia  2019    15   oecd                   inflow
...                  ...   ...   ...    ...                      ...
1025          Luxembourg  2021    14   oecd  citizenship_acquisition
1026           Australia  2016     3   oecd            worker_inflow
1027           Australia  2017     3   oecd            worker_inflow
1028           Australia  2018     3   oecd            worker_inflow
1029           Australia  2019     3   oecd            worker_inflow

[1030 rows x 5 columns]

## 12. Quality Checks After Cleaning

At this stage, the cleaned dataset should be checked before export.

Recommended checks include:

- verifying that all rows relate to Cameroon
- checking the year coverage
- checking missing values in key columns
- checking duplicated records
- verifying that `value` is numeric
- checking the distribution of the `nature` categories
- confirming that OECD indicators are not mixed with Eurostat or UN DESA indicators without clear methodological justification

These checks are important because OECD contains multiple indicators that should not be interpreted as one single migration measure.

## 13. Output Export

The cleaned OECD dataset is exported to the processed data folder.

Output file:

```text
data/processed/cleaned/oecd_migration_cleaned.csv
```

This file can later be used as complementary evidence in the exploratory analysis and reporting steps.

In [ ]:
sheet1_raw.to_csv(
    CLEANED_PATH / "oecd_migration_cleaned.csv",
    index=False
)

## 14. Limitations

The OECD dataset should be interpreted carefully.

Main limitations:

- OECD coverage is limited to OECD countries.
- The dataset contains several indicators that do not measure the same phenomenon.
- Inflows, outflows, stocks and citizenship acquisition should not be added together.
- OECD indicators may not be directly comparable with UN DESA or Eurostat indicators.
- The data does not reconstruct individual migrant journeys.

For these reasons, OECD data is treated as complementary evidence rather than as a single master source for the entire project.

## 15. Conclusion

This notebook produces a cleaned OECD migration dataset focused on Cameroon-related records.

The cleaned output is ready for later use in the analytical pipeline, mainly as complementary evidence for migration trends involving OECD destination countries.

The notebook also preserves a clear distinction between OECD indicators and the other institutional sources used in the project.